# Generated by Django 6.0.4 on 2026-04-26 12:52

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ApiAccessControl",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "permissions": [
                    ("read_api", "Can read API"),
                    ("write_api", "Can write API"),
                ],
            },
        ),
        migrations.CreateModel(
            name="OutboxEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique event ID, also used as cursor for pagination",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "idempotency_key",
                    models.CharField(
                        help_text="Unique key to prevent duplicate events (e.g., 'message.item.created:{message_id}')",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        db_index=True,
                        help_text="Event type (e.g., 'message.item.created', 'simulation.status.updated')",
                        max_length=100,
                    ),
                ),
                ("payload", models.JSONField(help_text="Event payload as JSON")),
                (
                    "simulation_id",
                    models.PositiveBigIntegerField(
                        db_index=True,
                        help_text="Simulation ID for routing to correct WebSocket group",
                    ),
                ),
                (
                    "correlation_id",
                    models.CharField(
                        blank=True,
                        help_text="Request correlation ID for tracing",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("delivered", "Delivered"),
                            ("failed", "Failed"),
                        ],
                        db_index=True,
                        default="pending",
                        help_text="Current delivery status",
                        max_length=20,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="When the event was created",
                    ),
                ),
                (
                    "delivered_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="When the event was successfully delivered",
                        null=True,
                    ),
                ),
                (
                    "delivery_attempts",
                    models.PositiveIntegerField(
                        default=0, help_text="Number of delivery attempts"
                    ),
                ),
                (
                    "last_error",
                    models.TextField(
                        blank=True, help_text="Last delivery error message", null=True
                    ),
                ),
            ],
            options={
                "verbose_name": "Outbox Event",
                "verbose_name_plural": "Outbox Events",
                "ordering": ["created_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "created_at"],
                        name="outbox_status_created_idx",
                    ),
                    models.Index(
                        fields=["simulation_id", "created_at"],
                        name="outbox_sim_created_idx",
                    ),
                    models.Index(
                        condition=models.Q(("delivered_at__isnull", False)),
                        fields=["delivered_at"],
                        name="outbox_delivered_idx",
                    ),
                ],
            },
        ),
    ]
