# Generated by Django 6.0.3 on 2026-03-23 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outboxevent',
            name='event_type',
            field=models.CharField(db_index=True, help_text="Event type (e.g., 'message.item.created', 'simulation.status.updated')", max_length=100),
        ),
        migrations.AlterField(
            model_name='outboxevent',
            name='idempotency_key',
            field=models.CharField(help_text="Unique key to prevent duplicate events (e.g., 'message.item.created:{message_id}')", max_length=255, unique=True),
        ),
    ]
