[project]
name = "SimWorks"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.13"
dependencies = [
    "channels>=4.2.2",
    "channels-redis>=4.2.1",
    "daphne>=4.1.2",
    "django>=5.2",
    "django-htmx>=1.23.0",
    "django-redis>=5.4.0",
    "faker>=37.1.0",
    "httpcore>=1.0.8",
    "openai>=1.76.0",
    "pre-commit>=4.2.0",
    "psycopg>=3.2.6",
    "psycopg-binary>=3.2.6",
    "pydantic>=2.11.3",
    "pytest>=8.3.5",
    "redis>=5.2.1",
    "typing-extensions>=4.13.2",
    "zope-interface>=7.2",
]
