[project]
name = "sim-works"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.13"
dependencies = [
    "django>=5.1.7",
    "psycopg>=3.2.6",
    "psycopg-binary>=3.2.6",
]
