# Generated by Django 5.2.4 on 2025-07-14 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Response',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('raw', models.JSONField(verbose_name='OpenAI Raw Response')),
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='OpenAI Response ID')),
                ('order', models.PositiveIntegerField(editable=False)),
                ('type', models.CharField(choices=[('I', 'initial'), ('R', 'reply'), ('F', 'feedback'), ('M', 'media'), ('TR', 'patient results')], default='R', max_length=2)),
                ('input_tokens', models.PositiveIntegerField(default=0)),
                ('output_tokens', models.PositiveIntegerField(default=0)),
                ('reasoning_tokens', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ('simulation', 'order'),
            },
        ),
    ]
