# Generated by Django 5.2.4 on 2025-07-22 21:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('simai', '0001_initial'),
        ('simcore', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='simulation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='simcore.simulation'),
        ),
        migrations.AddField(
            model_name='response',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='response',
            index=models.Index(fields=['created'], name='simai_respo_created_c296a4_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='response',
            unique_together={('simulation', 'order')},
        ),
    ]
