# Generated by Django 5.2 on 2025-04-18 18:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ChatLab', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Response',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('raw', models.TextField(verbose_name='OpenAI Raw Response')),
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='OpenAI Response ID')),
                ('order', models.PositiveIntegerField(editable=False)),
                ('input_tokens', models.PositiveIntegerField(default=0)),
                ('output_tokens', models.PositiveIntegerField(default=0)),
                ('reasoning_tokens', models.PositiveIntegerField(default=0)),
                ('simulation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='ChatLab.simulation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('simulation', 'order'),
                'indexes': [models.Index(fields=['created'], name='SimManAI_re_created_fe8144_idx')],
                'unique_together': {('simulation', 'order')},
            },
        ),
    ]
