# Generated by Django 6.0.4 on 2026-04-26 23:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chatlab', '0001_initial'),
        ('orchestrai_django', '0001_initial'),
        ('simcore', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='simulation',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_session', related_query_name='%(app_label)s_session', to='simcore.simulation'),
        ),
        migrations.AddField(
            model_name='message',
            name='conversation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='simcore.conversation'),
        ),
        migrations.AddField(
            model_name='message',
            name='sender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='message',
            name='service_call_attempt',
            field=models.ForeignKey(blank=True, help_text='Link to service call attempt that produced this message', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='orchestrai_django.servicecallattempt'),
        ),
        migrations.AddField(
            model_name='message',
            name='simulation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='input', to='simcore.simulation'),
        ),
        migrations.AddField(
            model_name='message',
            name='source_message',
            field=models.ForeignKey(blank=True, help_text='Source message this message was derived from (e.g., generated image).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='derived_messages', to='chatlab.message'),
        ),
        migrations.AddField(
            model_name='messagemedialink',
            name='media',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simcore.simulationimage'),
        ),
        migrations.AddField(
            model_name='messagemedialink',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chatlab.message'),
        ),
        migrations.AddField(
            model_name='message',
            name='media',
            field=models.ManyToManyField(blank=True, related_name='input', through='chatlab.MessageMediaLink', to='simcore.simulationimage'),
        ),
        migrations.AlterUniqueTogether(
            name='messagemedialink',
            unique_together={('message', 'media')},
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['simulation', 'timestamp'], name='chatlab_msg_sim_ts_idx'),
        ),
        migrations.AddConstraint(
            model_name='message',
            constraint=models.UniqueConstraint(condition=models.Q(('is_from_ai', True), ('message_type', 'image'), ('source_message__isnull', False)), fields=('source_message',), name='chatlab_unique_ai_image_per_source_message'),
        ),
    ]
