# Generated by Django 6.0.2 on 2026-02-22 23:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("chatlab", "0001_initial"),
        ("orchestrai_django", "0001_initial"),
        ("simcore", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="chatsession",
            name="simulation",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_session",
                related_query_name="%(app_label)s_session",
                to="simcore.simulation",
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="sender",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="service_call_attempt",
            field=models.ForeignKey(
                blank=True,
                help_text="Link to service call attempt that produced this message",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="messages",
                to="orchestrai_django.servicecallattempt",
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="simulation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="input",
                to="simcore.simulation",
            ),
        ),
        migrations.AddField(
            model_name="messagemedialink",
            name="media",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="simcore.simulationimage"
            ),
        ),
        migrations.AddField(
            model_name="messagemedialink",
            name="message",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="chatlab.message"
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="media",
            field=models.ManyToManyField(
                blank=True,
                related_name="input",
                through="chatlab.MessageMediaLink",
                to="simcore.simulationimage",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="messagemedialink",
            unique_together={("message", "media")},
        ),
    ]
