# Generated by Django 6.0.4 on 2026-08-29 13:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatlab', '0002_initial'),
        ('simcore', '0011_modifier_models'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VoiceSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('configuring', 'Configuring'), ('active', 'Active'), ('ended', 'Ended'), ('failed', 'Failed')], db_index=True, default='configuring', max_length=16)),
                ('transport', models.CharField(choices=[('webrtc', 'WebRTC'), ('websocket', 'WebSocket')], default='webrtc', max_length=16)),
                ('provider', models.CharField(default='openai', max_length=32)),
                ('provider_session_id', models.CharField(blank=True, default='', max_length=255)),
                ('model_name', models.CharField(blank=True, default='', max_length=100)),
                ('voice_name', models.CharField(blank=True, default='', max_length=100)),
                ('client_metadata', models.JSONField(blank=True, default=dict)),
                ('provider_metadata', models.JSONField(blank=True, default=dict)),
                ('last_error_code', models.CharField(blank=True, default='', max_length=100)),
                ('last_error_text', models.TextField(blank=True, default='')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voice_sessions', to='simcore.conversation')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chatlab_voice_sessions', to=settings.AUTH_USER_MODEL)),
                ('simulation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voice_sessions', to='simcore.simulation')),
            ],
            options={
                'ordering': ['-created_at', '-pk'],
                'indexes': [models.Index(fields=['simulation', 'status', 'created_at'], name='chatlab_voice_sim_status_idx'), models.Index(fields=['created_by', 'created_at'], name='chatlab_voice_actor_idx')],
            },
        ),
    ]
