# Generated by Django 6.0.5 on 2026-08-29 18:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatlab', '0003_voicesession'),
        ('simcore', '0011_modifier_models'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VoiceToolCall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tool_call_id', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=100)),
                ('arguments', models.JSONField(blank=True, default=dict)),
                ('output', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='running', max_length=16)),
                ('last_error_text', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='VoiceTranscriptReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_message_id', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at', '-pk'],
            },
        ),
        migrations.AddField(
            model_name='voicesession',
            name='client_idempotency_key',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddIndex(
            model_name='voicesession',
            index=models.Index(fields=['created_by', 'simulation', 'client_idempotency_key'], name='chatlab_voice_idem_idx'),
        ),
        migrations.AddConstraint(
            model_name='voicesession',
            constraint=models.UniqueConstraint(condition=models.Q(('client_idempotency_key__gt', '')), fields=('created_by', 'simulation', 'client_idempotency_key'), name='chatlab_unique_voice_start_idem'),
        ),
        migrations.AddField(
            model_name='voicetoolcall',
            name='voice_session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tool_calls', to='chatlab.voicesession'),
        ),
        migrations.AddField(
            model_name='voicetranscriptreceipt',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voice_transcript_receipts', to='chatlab.message'),
        ),
        migrations.AddField(
            model_name='voicetranscriptreceipt',
            name='voice_session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transcript_receipts', to='chatlab.voicesession'),
        ),
        migrations.AddIndex(
            model_name='voicetoolcall',
            index=models.Index(fields=['voice_session', 'status'], name='chatlab_voice_tool_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='voicetoolcall',
            constraint=models.UniqueConstraint(fields=('voice_session', 'tool_call_id'), name='chatlab_unique_voice_tool_call'),
        ),
        migrations.AddConstraint(
            model_name='voicetranscriptreceipt',
            constraint=models.UniqueConstraint(fields=('voice_session', 'provider_message_id'), name='chatlab_unique_voice_transcript'),
        ),
    ]
