# Generated by Django 6.0.5 on 2026-08-30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chatlab", "0004_voicetoolcall_voicetranscriptreceipt_and_more"),
        ("simcore", "0012_conversation_provider_state"),
    ]

    operations = [
        migrations.AddField(
            model_name="voicesession",
            name="responses_sync_cursor",
            field=models.PositiveBigIntegerField(
                blank=True,
                help_text="Canonical Message ID known to be in Responses when this voice session branched.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="voicesession",
            name="responses_sync_error",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="voicesession",
            name="responses_sync_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("synced", "Synced"),
                    ("failed", "Failed"),
                ],
                db_index=True,
                default="pending",
                max_length=16,
            ),
        ),
        migrations.CreateModel(
            name="ProviderConversationItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("provider_conversation_id", models.CharField(max_length=255)),
                ("provider_item_id", models.CharField(max_length=255)),
                ("item_type", models.CharField(default="message", max_length=32)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "conversation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="provider_items",
                        to="simcore.conversation",
                    ),
                ),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="provider_conversation_items",
                        to="chatlab.message",
                    ),
                ),
            ],
            options={"ordering": ["message_id", "pk"]},
        ),
        migrations.AddConstraint(
            model_name="providerconversationitem",
            constraint=models.UniqueConstraint(
                fields=("conversation", "message", "provider_conversation_id"),
                name="chatlab_unique_provider_message_sync",
            ),
        ),
        migrations.AddConstraint(
            model_name="providerconversationitem",
            constraint=models.UniqueConstraint(
                fields=("provider_conversation_id", "provider_item_id"),
                name="chatlab_unique_provider_item_id",
            ),
        ),
    ]
