# Generated by Django 6.0.3 on 2026-03-12 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chatlab", "0005_message_delivery_error_code_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="source_message",
            field=models.ForeignKey(
                blank=True,
                help_text="Source message this message was derived from (e.g., generated image).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="derived_messages",
                to="chatlab.message",
            ),
        ),
        migrations.AddConstraint(
            model_name="message",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("is_from_ai", True),
                    ("message_type", "image"),
                    ("source_message__isnull", False),
                ),
                fields=("source_message",),
                name="chatlab_unique_ai_image_per_source_message",
            ),
        ),
    ]
