# Generated by Django 6.0.5 on 2026-08-30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chatlab", "0005_provider_conversation_sync"),
    ]

    operations = [
        migrations.AddField(
            model_name="voicetranscriptreceipt",
            name="metadata",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
