# Generated by Django 6.0.4 on 2026-04-26 12:52

import apps.simcore.models
import autoslug.fields
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("contenttypes", "0002_remove_content_type_name"),
        ("orchestrai_django", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ConversationType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(max_length=40, unique=True)),
                ("display_name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        help_text="Iconify icon identifier, e.g. 'mdi:robot'",
                        max_length=50,
                    ),
                ),
                (
                    "ai_persona",
                    models.CharField(
                        blank=True,
                        help_text="AI persona slug for service dispatch (e.g. 'patient', 'stitch')",
                        max_length=40,
                    ),
                ),
                (
                    "locks_with_simulation",
                    models.BooleanField(
                        default=True,
                        help_text="If True, conversation becomes read-only when simulation ends",
                    ),
                ),
                (
                    "available_in",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Lab apps where this type is available, e.g. ['chatlab', 'trainerlab']",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("sort_order", models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                "verbose_name": "Conversation Type",
                "verbose_name_plural": "Conversation Types",
                "ordering": ["sort_order", "slug"],
            },
        ),
        migrations.CreateModel(
            name="SimulationMetadata",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("key", models.CharField(max_length=255)),
                ("value", models.TextField()),
                (
                    "polymorphic_ctype",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="polymorphic_%(app_label)s.%(class)s_set+",
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "service_call_attempt",
                    models.ForeignKey(
                        blank=True,
                        help_text="Link to service call attempt that produced this metadata",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="simulation_metadata",
                        to="orchestrai_django.servicecallattempt",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Simulation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_timestamp", models.DateTimeField(auto_now_add=True)),
                ("end_timestamp", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("timed_out", "Timed Out"),
                            ("failed", "Failed"),
                            ("canceled", "Canceled"),
                        ],
                        db_index=True,
                        default="in_progress",
                        max_length=24,
                    ),
                ),
                (
                    "terminal_reason_code",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("terminal_reason_text", models.TextField(blank=True, default="")),
                ("terminal_at", models.DateTimeField(blank=True, null=True)),
                (
                    "archived_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "archived_reason",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("system_failed", "System: Failed"),
                            ("user_archived", "User Archived"),
                            ("staff_archived", "Staff Archived"),
                        ],
                        db_index=True,
                        default="",
                        max_length=32,
                    ),
                ),
                ("initial_retry_count", models.PositiveSmallIntegerField(default=0)),
                ("feedback_retry_count", models.PositiveSmallIntegerField(default=0)),
                (
                    "time_limit",
                    models.DurationField(
                        blank=True,
                        help_text="Optional max duration for this simulation",
                        null=True,
                    ),
                ),
                (
                    "openai_model",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                (
                    "metadata_checksum",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                (
                    "prompt_instruction",
                    models.TextField(
                        default="", help_text="The prompt to use as AI instructions"
                    ),
                ),
                (
                    "prompt_message",
                    models.TextField(
                        blank=True,
                        help_text="The prompt to use as AI message",
                        null=True,
                    ),
                ),
                (
                    "prompt_meta",
                    models.JSONField(
                        blank=True,
                        help_text="The prompt metadata to use as AI message",
                        null=True,
                    ),
                ),
                ("diagnosis", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "chief_complaint",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("sim_patient_full_name", models.CharField(blank=True, max_length=100)),
                (
                    "sim_patient_display_name",
                    models.CharField(blank=True, max_length=100),
                ),
                (
                    "account",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="simulations",
                        to="accounts.account",
                    ),
                ),
                (
                    "archived_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="archived_simulations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LabResult",
            fields=[
                (
                    "simulationmetadata_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="simcore.simulationmetadata",
                    ),
                ),
                ("panel_name", models.CharField(blank=True, max_length=100, null=True)),
                ("result_unit", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "reference_range_low",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "reference_range_high",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("result_flag", models.CharField(max_length=20)),
                ("result_comment", models.TextField(blank=True, null=True)),
            ],
            options={
                "abstract": False,
            },
            bases=("simcore.simulationmetadata",),
        ),
        migrations.CreateModel(
            name="PatientDemographics",
            fields=[
                (
                    "simulationmetadata_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="simcore.simulationmetadata",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("simcore.simulationmetadata",),
        ),
        migrations.CreateModel(
            name="PatientHistory",
            fields=[
                (
                    "simulationmetadata_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="simcore.simulationmetadata",
                    ),
                ),
                ("is_resolved", models.BooleanField(default=False)),
                ("duration", models.CharField(max_length=100)),
            ],
            options={
                "abstract": False,
            },
            bases=("simcore.simulationmetadata",),
        ),
        migrations.CreateModel(
            name="RadResult",
            fields=[
                (
                    "simulationmetadata_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="simcore.simulationmetadata",
                    ),
                ),
                ("result_flag", models.CharField(max_length=10)),
            ],
            options={
                "abstract": False,
            },
            bases=("simcore.simulationmetadata",),
        ),
        migrations.AddField(
            model_name="simulationmetadata",
            name="simulation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="metadata",
                to="simcore.simulation",
            ),
        ),
        migrations.CreateModel(
            name="Conversation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("display_name", models.CharField(blank=True, max_length=100)),
                ("display_initials", models.CharField(blank=True, max_length=5)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_archived", models.BooleanField(default=False)),
                (
                    "conversation_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="conversations",
                        to="simcore.conversationtype",
                    ),
                ),
                (
                    "simulation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conversations",
                        to="simcore.simulation",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="SimulationImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("mime_type", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "provider_id",
                    models.CharField(
                        blank=True,
                        help_text="OpenAI image ID (if applicable)",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        help_text="Unique identifier for this image",
                        unique=True,
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        help_text="3-5 words describing the image",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "slug",
                    autoslug.fields.AutoSlugField(
                        always_update=True,
                        editable=False,
                        populate_from=apps.simcore.models.slug_source,
                        unique_with=("simulation",),
                    ),
                ),
                (
                    "original",
                    models.ImageField(
                        height_field="original_height",
                        upload_to=apps.simcore.models.get_image_path,
                        verbose_name="image",
                        width_field="original_width",
                    ),
                ),
                (
                    "original_height",
                    models.PositiveIntegerField(blank=True, editable=False, null=True),
                ),
                (
                    "original_width",
                    models.PositiveIntegerField(blank=True, editable=False, null=True),
                ),
                (
                    "simulation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="simcore.simulation",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SimulationSummary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("summary_text", models.TextField(blank=True, default="")),
                (
                    "chief_complaint",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("diagnosis", models.CharField(blank=True, default="", max_length=255)),
                ("strengths", models.JSONField(blank=True, default=list)),
                ("improvement_areas", models.JSONField(blank=True, default=list)),
                ("learning_points", models.JSONField(blank=True, default=list)),
                (
                    "recommended_study_topics",
                    models.JSONField(blank=True, default=list),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "simulation",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="summary",
                        to="simcore.simulation",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="simulationmetadata",
            constraint=models.UniqueConstraint(
                fields=("simulation", "key"), name="uniq_simulation_key"
            ),
        ),
        migrations.AddIndex(
            model_name="simulation",
            index=models.Index(
                fields=["account", "start_timestamp"], name="idx_sim_account_started"
            ),
        ),
        migrations.AddIndex(
            model_name="simulation",
            index=models.Index(
                fields=["account", "status"], name="idx_sim_account_status"
            ),
        ),
        migrations.AddIndex(
            model_name="simulation",
            index=models.Index(
                fields=["status", "archived_at"], name="idx_sim_status_archived"
            ),
        ),
        migrations.AddIndex(
            model_name="conversation",
            index=models.Index(
                fields=["simulation", "conversation_type"], name="idx_conv_sim_type"
            ),
        ),
        migrations.AddConstraint(
            model_name="conversation",
            constraint=models.UniqueConstraint(
                fields=("simulation", "conversation_type"),
                name="uniq_conversation_simulation_type",
            ),
        ),
    ]
