# Generated by Django 6.0.2 on 2026-03-02 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("simcore", "0003_seed_conversation_types"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="conversation",
            constraint=models.UniqueConstraint(
                fields=("simulation", "conversation_type"),
                name="uniq_conversation_simulation_type",
            ),
        ),
    ]
