# Generated by Django 6.0.2 on 2026-03-03 15:00

from django.db import migrations, models
from django.utils import timezone


def _backfill_simulation_status(apps, schema_editor):
    Simulation = apps.get_model("simcore", "Simulation")
    now = timezone.now()

    for sim in Simulation.objects.all().iterator():
        # Preserve explicitly set values if present.
        if sim.status and sim.status != "in_progress":
            continue

        update_fields = []

        if sim.end_timestamp:
            timeout_cutoff = (
                sim.start_timestamp + sim.time_limit
                if sim.time_limit and sim.start_timestamp
                else None
            )
            if timeout_cutoff and sim.end_timestamp >= timeout_cutoff:
                sim.status = "timed_out"
                sim.terminal_reason_code = "timed_out"
                sim.terminal_reason_text = "Simulation timed out."
            else:
                sim.status = "completed"
            sim.terminal_at = sim.end_timestamp
            update_fields.extend(
                [
                    "status",
                    "terminal_reason_code",
                    "terminal_reason_text",
                    "terminal_at",
                ]
            )
        elif sim.time_limit and sim.start_timestamp and (sim.start_timestamp + sim.time_limit) < now:
            timed_out_at = sim.start_timestamp + sim.time_limit
            sim.status = "timed_out"
            sim.end_timestamp = timed_out_at
            sim.terminal_at = timed_out_at
            sim.terminal_reason_code = "timed_out"
            sim.terminal_reason_text = "Simulation timed out."
            update_fields.extend(
                [
                    "status",
                    "end_timestamp",
                    "terminal_at",
                    "terminal_reason_code",
                    "terminal_reason_text",
                ]
            )

        if update_fields:
            sim.save(update_fields=update_fields)


def _noop_reverse(apps, schema_editor):
    return None


class Migration(migrations.Migration):

    dependencies = [
        ('simcore', '0004_conversation_uniq_conversation_simulation_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulation',
            name='feedback_retry_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='simulation',
            name='initial_retry_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='simulation',
            name='status',
            field=models.CharField(choices=[('in_progress', 'In Progress'), ('completed', 'Completed'), ('timed_out', 'Timed Out'), ('failed', 'Failed'), ('canceled', 'Canceled')], db_index=True, default='in_progress', max_length=24),
        ),
        migrations.AddField(
            model_name='simulation',
            name='terminal_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='simulation',
            name='terminal_reason_code',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='simulation',
            name='terminal_reason_text',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.RunPython(_backfill_simulation_status, _noop_reverse),
    ]
