# Generated by Django 6.0.3 on 2026-03-20 08:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simcore', '0005_simulation_feedback_retry_count_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SimulationSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary_text', models.TextField(blank=True, default='')),
                ('chief_complaint', models.CharField(blank=True, default='', max_length=255)),
                ('diagnosis', models.CharField(blank=True, default='', max_length=255)),
                ('strengths', models.JSONField(blank=True, default=list)),
                ('improvement_areas', models.JSONField(blank=True, default=list)),
                ('learning_points', models.JSONField(blank=True, default=list)),
                ('recommended_study_topics', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('simulation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='summary', to='simcore.simulation')),
            ],
        ),
    ]
