# Generated by Django 6.0.3 on 2026-03-23 12:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_account_user_active_account_accountauditevent_and_more'),
        ('simcore', '0006_simulationsummary'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='simulation',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='simulations', to='accounts.account'),
        ),
        migrations.AlterField(
            model_name='simulation',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='simulation',
            index=models.Index(fields=['account', 'start_timestamp'], name='idx_sim_account_started'),
        ),
        migrations.AddIndex(
            model_name='simulation',
            index=models.Index(fields=['account', 'status'], name='idx_sim_account_status'),
        ),
    ]
