# Generated by Codex on 2026-03-23

from django.db import migrations


def forwards(apps, schema_editor):
    Simulation = apps.get_model("simcore", "Simulation")
    Account = apps.get_model("accounts", "Account")
    db_alias = schema_editor.connection.alias
    account_map = dict(
        Account.objects.using(db_alias)
        .filter(account_type="personal")
        .values_list("owner_user_id", "id")
    )

    queryset = (
        Simulation.objects.using(db_alias)
        .filter(account__isnull=True)
        .exclude(user__isnull=True)
        .order_by("id")
    )
    for simulation in queryset.iterator(chunk_size=500):
        account_id = account_map.get(simulation.user_id)
        if account_id is None:
            account_id = (
                Account.objects.using(db_alias)
                .filter(owner_user_id=simulation.user_id, account_type="personal")
                .values_list("id", flat=True)
                .first()
            )
            if account_id is None:
                continue
            account_map[simulation.user_id] = account_id
        Simulation.objects.using(db_alias).filter(
            pk=simulation.pk,
            account__isnull=True,
        ).update(account_id=account_id)


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ("accounts", "0004_backfill_personal_accounts"),
        ("simcore", "0007_simulation_account_alter_simulation_user_and_more"),
    ]

    operations = [
        migrations.RunPython(forwards, migrations.RunPython.noop),
    ]
