# Generated by Django 6.0.5 on 2026-08-30

from django.db import migrations, models
from django.db.models import Q


class Migration(migrations.Migration):

    dependencies = [
        ("simcore", "0011_modifier_models"),
    ]

    operations = [
        migrations.AddField(
            model_name="conversation",
            name="provider",
            field=models.CharField(
                blank=True,
                default="openai",
                help_text="Provider owning the optional durable runtime conversation.",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="conversation",
            name="provider_conversation_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                help_text="Provider conversation identifier; canonical history remains in MedSim.",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="conversation",
            name="provider_sync_cursor",
            field=models.PositiveBigIntegerField(
                blank=True,
                help_text="Highest canonical Message ID known to be present in the provider conversation.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="conversation",
            name="provider_sync_error",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="conversation",
            name="provider_sync_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("synced", "Synced"),
                    ("failed", "Failed"),
                ],
                db_index=True,
                default="pending",
                max_length=16,
            ),
        ),
        migrations.AddConstraint(
            model_name="conversation",
            constraint=models.UniqueConstraint(
                condition=Q(("provider_conversation_id__gt", "")),
                fields=("provider", "provider_conversation_id"),
                name="uniq_conversation_provider_runtime_id",
            ),
        ),
    ]
