# Generated by Django 6.0.4 on 2026-05-03 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simcore', '0011_modifier_models'),
        ('trainerlab', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='intervention',
            name='client_event_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddConstraint(
            model_name='intervention',
            constraint=models.UniqueConstraint(condition=models.Q(('client_event_id', ''), _negated=True), fields=('simulation', 'client_event_id'), name='uniq_intervention_sim_client_event'),
        ),
    ]
