# Generated by Django 6.0.2 on 2026-03-02 00:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainerlab', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='abcevent',
            options={},
        ),
        migrations.AlterModelOptions(
            name='bloodglucoselevel',
            options={},
        ),
        migrations.AlterModelOptions(
            name='etco2',
            options={},
        ),
        migrations.AlterModelOptions(
            name='heartrate',
            options={},
        ),
        migrations.AlterModelOptions(
            name='injury',
            options={},
        ),
        migrations.AlterModelOptions(
            name='intervention',
            options={},
        ),
        migrations.AlterModelOptions(
            name='spo2',
            options={},
        ),
    ]
