# Generated by Django 6.0.3 on 2026-03-06 23:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simcore', '0005_simulation_feedback_retry_count_and_more'),
        ('trainerlab', '0002_alter_abcevent_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Illness',
            fields=[
                ('abcevent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='trainerlab.abcevent')),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('moderate', 'Moderate'), ('high', 'High'), ('critical', 'Critical')], default='moderate', max_length=16)),
                ('is_resolved', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
            bases=('trainerlab.abcevent',),
        ),
        migrations.CreateModel(
            name='TrainerCommand',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('command_type', models.CharField(choices=[('create_session', 'Create Session'), ('start', 'Start'), ('pause', 'Pause'), ('resume', 'Resume'), ('stop', 'Stop'), ('steer_prompt', 'Steer Prompt'), ('inject_event', 'Inject Event')], max_length=32)),
                ('payload_json', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processed', 'Processed'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('idempotency_key', models.CharField(max_length=255, unique=True)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('error', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='TrainerRunSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary_json', models.JSONField(default=dict)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('generator_version', models.CharField(default='v1', max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='TrainerRuntimeEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(max_length=120)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('correlation_id', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddField(
            model_name='abcevent',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='abcevent',
            name='source',
            field=models.CharField(choices=[('ai', 'AI'), ('instructor', 'Instructor'), ('system', 'System')], default='system', max_length=16),
        ),
        migrations.AddField(
            model_name='abcevent',
            name='supersedes_event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='superseded_domain_events', to='trainerlab.abcevent'),
        ),
        migrations.AddField(
            model_name='intervention',
            name='code',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='intervention',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='intervention',
            name='target',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='trainersession',
            name='initial_directives',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='trainersession',
            name='last_ai_tick_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainersession',
            name='run_completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainersession',
            name='run_paused_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainersession',
            name='run_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainersession',
            name='runtime_state_json',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='trainersession',
            name='scenario_spec_json',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='trainersession',
            name='status',
            field=models.CharField(choices=[('seeded', 'Seeded'), ('running', 'Running'), ('paused', 'Paused'), ('completed', 'Completed'), ('failed', 'Failed')], default='seeded', max_length=16),
        ),
        migrations.AddField(
            model_name='trainersession',
            name='tick_interval_seconds',
            field=models.PositiveSmallIntegerField(default=15),
        ),
        migrations.AddField(
            model_name='trainersession',
            name='tick_nonce',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name='trainersession',
            index=models.Index(fields=['status'], name='idx_trainer_session_status'),
        ),
        migrations.AddIndex(
            model_name='trainersession',
            index=models.Index(fields=['run_started_at'], name='idx_trainer_session_started'),
        ),
        migrations.AddField(
            model_name='trainercommand',
            name='issued_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trainerlab_commands', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='trainercommand',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commands', to='trainerlab.trainersession'),
        ),
        migrations.AddField(
            model_name='trainerrunsummary',
            name='session',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='summary', to='trainerlab.trainersession'),
        ),
        migrations.AddField(
            model_name='trainerruntimeevent',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trainer_runtime_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='trainerruntimeevent',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runtime_events', to='trainerlab.trainersession'),
        ),
        migrations.AddField(
            model_name='trainerruntimeevent',
            name='simulation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trainer_runtime_events', to='simcore.simulation'),
        ),
        migrations.AddField(
            model_name='trainerruntimeevent',
            name='supersedes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='superseded_by', to='trainerlab.trainerruntimeevent'),
        ),
        migrations.AddIndex(
            model_name='trainercommand',
            index=models.Index(fields=['session', 'issued_at'], name='idx_trainer_cmd_session'),
        ),
        migrations.AddIndex(
            model_name='trainercommand',
            index=models.Index(fields=['status'], name='idx_trainer_cmd_status'),
        ),
        migrations.AddIndex(
            model_name='trainerruntimeevent',
            index=models.Index(fields=['simulation', 'created_at'], name='idx_trainer_evt_sim'),
        ),
        migrations.AddIndex(
            model_name='trainerruntimeevent',
            index=models.Index(fields=['session', 'created_at'], name='idx_trainer_evt_session'),
        ),
    ]
