# Generated by Django 6.0.5 on 2026-09-18 19:27

from django.conf import settings
from django.db import migrations, models


def number_existing_events(apps, schema_editor):
    RuntimeEvent = apps.get_model("trainerlab", "RuntimeEvent")
    TrainerSession = apps.get_model("trainerlab", "TrainerSession")
    for session in TrainerSession.objects.using(schema_editor.connection.alias).iterator():
        count = 0
        batch = []
        events = (
            RuntimeEvent.objects.using(schema_editor.connection.alias)
            .filter(session_id=session.pk)
            .order_by("created_at", "id")
            .iterator(chunk_size=500)
        )
        for event in events:
            count += 1
            event.sequence = count
            batch.append(event)
            if len(batch) == 500:
                RuntimeEvent.objects.using(schema_editor.connection.alias).bulk_update(batch, ["sequence"])
                batch.clear()
        if batch:
            RuntimeEvent.objects.using(schema_editor.connection.alias).bulk_update(batch, ["sequence"])
        if count:
            TrainerSession.objects.using(schema_editor.connection.alias).filter(pk=session.pk).update(
                event_sequence=count
            )


class Migration(migrations.Migration):

    dependencies = [
        ('simcore', '0011_modifier_models'),
        ('trainerlab', '0002_intervention_client_event_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='runtimeevent',
            name='sequence',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainersession',
            name='event_sequence',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.RunPython(number_existing_events, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='runtimeevent',
            constraint=models.UniqueConstraint(fields=('session', 'sequence'), name='uniq_tl_runtime_sequence'),
        ),
    ]
