# Generated by Django 6.0.5 on 2026-09-18 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainerlab', '0003_runtimeevent_sequence_trainersession_event_sequence_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='onset_elapsed_seconds',
            field=models.PositiveIntegerField(blank=True, help_text='Simulation clock time at first onset; carried through superseding records.', null=True),
        ),
    ]
