# Generated by Django 6.0.3 on 2026-03-09 15:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainerlab', '0003_illness_trainercommand_trainerrunsummary_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='injury',
            name='injury_location',
            field=models.CharField(choices=[('HLA', 'Left Anterior Head'), ('HRA', 'Right Anterior Head'), ('HLP', 'Left Posterior Head'), ('HRP', 'Right Posterior Head'), ('NLA', 'Left Anterior Neck'), ('NRA', 'Right Anterior Neck'), ('NLP', 'Left Posterior Neck'), ('NRP', 'Right Posterior Neck'), ('LUA', 'Left Upper Arm'), ('LLA', 'Left Lower Arm'), ('LHA', 'Left Hand'), ('RUA', 'Right Upper Arm'), ('RLA', 'Right Lower Arm'), ('RHA', 'Right Hand'), ('TLA', 'Left Anterior Chest'), ('TRA', 'Right Anterior Chest'), ('TLP', 'Left Posterior Chest'), ('TRP', 'Right Posterior Chest'), ('ALA', 'Left Anterior Abdomen'), ('ARA', 'Right Anterior Abdomen'), ('ALP', 'Left Posterior Abdomen'), ('ARP', 'Right Posterior Abdomen'), ('LUL', 'Left Upper Leg'), ('LLL', 'Left Lower Leg'), ('LFT', 'Left Foot'), ('RUL', 'Right Upper Leg'), ('RLL', 'Right Lower Leg'), ('RFT', 'Right Foot'), ('JLX', 'Left Junctional Axilla'), ('JRX', 'Right Junctional Axilla'), ('JLI', 'Left Junctional Inguinal'), ('JRI', 'Right Junctional Inguinal'), ('JLN', 'Left Junctional Neck'), ('JRN', 'Right Junctional Neck')], db_index=True, help_text='The location of the injury', max_length=4),
        ),
        migrations.AlterField(
            model_name='trainercommand',
            name='command_type',
            field=models.CharField(choices=[('create_session', 'Create Session'), ('start', 'Start'), ('pause', 'Pause'), ('resume', 'Resume'), ('stop', 'Stop'), ('steer_prompt', 'Steer Prompt'), ('inject_event', 'Inject Event'), ('adjust_scenario', 'Adjust Scenario'), ('apply_preset', 'Apply Preset')], max_length=32),
        ),
        migrations.CreateModel(
            name='ScenarioInstruction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, default='')),
                ('instruction_text', models.TextField(blank=True, default='')),
                ('injuries_json', models.JSONField(blank=True, default=list)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('moderate', 'Moderate'), ('high', 'High'), ('critical', 'Critical')], default='moderate', max_length=16)),
                ('metadata_json', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trainer_scenario_instructions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-modified_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='ScenarioInstructionPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_read', models.BooleanField(default=True)),
                ('can_edit', models.BooleanField(default=False)),
                ('can_delete', models.BooleanField(default=False)),
                ('can_share', models.BooleanField(default=False)),
                ('can_duplicate', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('granted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_trainer_scenario_permissions', to=settings.AUTH_USER_MODEL)),
                ('scenario_instruction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='trainerlab.scenarioinstruction')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trainer_scenario_instruction_permissions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='scenarioinstruction',
            index=models.Index(fields=['owner', 'is_active'], name='idx_scenario_owner_active'),
        ),
        migrations.AddIndex(
            model_name='scenarioinstruction',
            index=models.Index(fields=['severity'], name='idx_scenario_severity'),
        ),
        migrations.AddIndex(
            model_name='scenarioinstructionpermission',
            index=models.Index(fields=['user', 'can_read'], name='idx_scenario_perm_user_read'),
        ),
        migrations.AddIndex(
            model_name='scenarioinstructionpermission',
            index=models.Index(fields=['scenario_instruction', 'can_share'], name='idx_scenario_perm_share'),
        ),
        migrations.AddConstraint(
            model_name='scenarioinstructionpermission',
            constraint=models.UniqueConstraint(fields=('scenario_instruction', 'user'), name='uniq_trainer_scenario_permission'),
        ),
    ]
