# Generated by Django 6.0.5 on 2026-09-19 12:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainerlab', '0004_problem_onset_elapsed_seconds'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScenarioDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_revision', models.PositiveIntegerField(default=0)),
                ('proposal', models.JSONField(default=dict)),
                ('status', models.CharField(default='pending', max_length=24)),
                ('source_call_id', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scenario_decisions', to='trainerlab.trainersession')),
            ],
        ),
        migrations.CreateModel(
            name='ProgressionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField()),
                ('input_revision', models.PositiveIntegerField(default=0)),
                ('starts_at', models.PositiveIntegerField()),
                ('ends_at', models.PositiveIntegerField()),
                ('status', models.CharField(default='active', max_length=24)),
                ('baseline', models.JSONField(default=list)),
                ('targets', models.JSONField(default=list)),
                ('portrayal', models.JSONField(default=dict)),
                ('source_call_id', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progression_plans', to='trainerlab.trainersession')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('session', 'version'), name='uniq_tl_plan_version'), models.UniqueConstraint(fields=('session',), condition=models.Q(status='active'), name='uniq_tl_active_plan'), models.CheckConstraint(condition=models.Q(ends_at__gt=models.F('starts_at')), name='tl_plan_positive_horizon')],
            },
        ),
    ]
