# Generated by Django 6.0.2 on 2026-03-12 00:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("trainerlab", "0004_alter_injury_injury_location_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="RespiratoryRate",
            fields=[
                (
                    "vitalmeasurement_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="trainerlab.vitalmeasurement",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "base_manager_name": "objects",
            },
            bases=("trainerlab.vitalmeasurement",),
        ),
    ]
