# Generated by Django 6.0.3 on 2026-03-13 01:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("trainerlab", "0005_respiratoryrate"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="respiratoryrate",
            options={},
        ),
    ]
