# Generated by Django 6.0.3 on 2026-03-14 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainerlab', '0006_alter_respiratoryrate_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='intervention',
            name='anatomic_location',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='intervention',
            name='effective',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='intervention',
            name='performed_by_role',
            field=models.CharField(choices=[('trainee', 'Trainee'), ('instructor', 'Instructor'), ('ai', 'AI')], default='trainee', max_length=16),
        ),
    ]
