# Generated by Django 6.0.3 on 2026-03-14 20:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trainerlab", "0007_intervention_anatomic_location_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SimulationNote",
            fields=[
                (
                    "abcevent_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="trainerlab.abcevent",
                    ),
                ),
                ("content", models.TextField(max_length=2000)),
            ],
            options={
                "abstract": False,
            },
            bases=("trainerlab.abcevent",),
        ),
    ]
