# Generated by Django 6.0.3

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trainerlab", "0008_simulationnote"),
    ]

    operations = [
        migrations.CreateModel(
            name="ScenarioBrief",
            fields=[
                (
                    "abcevent_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="trainerlab.abcevent",
                    ),
                ),
                (
                    "read_aloud_brief",
                    models.TextField(
                        help_text="Concise instructor read-aloud brief for the trainee."
                    ),
                ),
                ("environment", models.TextField(blank=True, default="")),
                ("location_overview", models.TextField(blank=True, default="")),
                ("threat_context", models.TextField(blank=True, default="")),
                (
                    "evacuation_options",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Available evacuation or transport options.",
                    ),
                ),
                (
                    "evacuation_time",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "special_considerations",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Other constraints or scenario considerations.",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("trainerlab.abcevent",),
        ),
    ]
