# Generated by Django 6.0.3

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trainerlab", "0009_scenariobrief"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="intervention",
            name="effective",
        ),
        migrations.AddField(
            model_name="intervention",
            name="intervention_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("tourniquet", "Tourniquet"),
                    ("wound_packing", "Wound Packing"),
                    ("pressure_dressing", "Pressure Dressing"),
                    ("npa", "Nasopharyngeal Airway"),
                    ("opa", "Oropharyngeal Airway"),
                    ("needle_decompression", "Needle Decompression"),
                    ("surgical_cric", "Surgical Cricothyrotomy"),
                ],
                db_index=True,
                default="",
                max_length=64,
            ),
        ),
        migrations.AddField(
            model_name="intervention",
            name="site_code",
            field=models.CharField(blank=True, db_index=True, default="", max_length=64),
        ),
        migrations.AddField(
            model_name="intervention",
            name="target_injury",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="targeted_by_interventions",
                to="trainerlab.injury",
            ),
        ),
        migrations.AddField(
            model_name="intervention",
            name="status",
            field=models.CharField(
                choices=[
                    ("applied", "Applied"),
                    ("adjusted", "Adjusted"),
                    ("reassessed", "Reassessed"),
                    ("removed", "Removed"),
                ],
                default="applied",
                max_length=24,
            ),
        ),
        migrations.AddField(
            model_name="intervention",
            name="effectiveness",
            field=models.CharField(
                choices=[
                    ("unknown", "Unknown"),
                    ("effective", "Effective"),
                    ("partially_effective", "Partially Effective"),
                    ("ineffective", "Ineffective"),
                ],
                default="unknown",
                max_length=24,
            ),
        ),
        migrations.AddField(
            model_name="intervention",
            name="notes",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="intervention",
            name="details_json",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
