# Generated by Django 6.0.3

from django.db import migrations


class Migration(migrations.Migration):
    """
    No-op migration. The composite indexes on Intervention that referenced
    'simulation' (a non-local field from parent model ABCEvent) were removed
    from migration 0010 before being applied, so there is nothing to remove here.

    Multi-table inheritance prohibits non-local fields in Meta.indexes (models.E016).
    The individual fields (intervention_type, site_code) carry db_index=True so
    no query-performance regression occurs.
    """

    dependencies = [
        ("trainerlab", "0010_intervention_structured_fields"),
    ]

    operations = []
