# Generated by Django 6.0.3 on 2026-03-16 11:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trainerlab", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="intervention",
            name="intervention_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("tourniquet", "Tourniquet"),
                    ("wound_packing", "Wound Packing"),
                    ("pressure_dressing", "Pressure Dressing"),
                    ("npa", "Nasopharyngeal Airway"),
                    ("opa", "Oropharyngeal Airway"),
                    ("needle_decompression", "Needle Decompression"),
                    ("surgical_cric", "Surgical Cricothyrotomy"),
                    ("junctional_tourniquet", "Junctional Tourniquet"),
                    ("hemostatic_agent", "Hemostatic Agent"),
                    ("pelvic_binder", "Pelvic Binder"),
                    ("iv_access", "IV Access"),
                    ("io_access", "IO Access"),
                    ("fluid_resuscitation", "Fluid Resuscitation"),
                    ("blood_transfusion", "Blood Transfusion / WBCT"),
                    ("advanced_airway", "Advanced Airway"),
                    ("chest_tube", "Chest Tube / Finger Thoracostomy"),
                ],
                db_index=True,
                default="",
                max_length=64,
            ),
        ),
        migrations.CreateModel(
            name="PulseAssessment",
            fields=[
                (
                    "abcevent_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="trainerlab.abcevent",
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        choices=[
                            ("radial_left", "Radial (Left)"),
                            ("radial_right", "Radial (Right)"),
                            ("femoral_left", "Femoral (Left)"),
                            ("femoral_right", "Femoral (Right)"),
                            ("carotid_left", "Carotid (Left)"),
                            ("carotid_right", "Carotid (Right)"),
                            ("pedal_left", "Pedal (Left)"),
                            ("pedal_right", "Pedal (Right)"),
                        ],
                        max_length=20,
                    ),
                ),
                ("present", models.BooleanField()),
                (
                    "description",
                    models.CharField(
                        choices=[
                            ("strong", "Strong"),
                            ("bounding", "Bounding"),
                            ("weak", "Weak"),
                            ("absent", "Absent"),
                            ("thready", "Thready"),
                        ],
                        max_length=20,
                    ),
                ),
                ("color_normal", models.BooleanField()),
                (
                    "color_description",
                    models.CharField(
                        choices=[
                            ("pink", "Pink"),
                            ("pale", "Pale"),
                            ("mottled", "Mottled"),
                            ("cyanotic", "Cyanotic"),
                            ("flushed", "Flushed"),
                        ],
                        max_length=20,
                    ),
                ),
                ("condition_normal", models.BooleanField()),
                (
                    "condition_description",
                    models.CharField(
                        choices=[
                            ("dry", "Dry"),
                            ("moist", "Moist"),
                            ("diaphoretic", "Diaphoretic"),
                            ("clammy", "Clammy"),
                        ],
                        max_length=20,
                    ),
                ),
                ("temperature_normal", models.BooleanField()),
                (
                    "temperature_description",
                    models.CharField(
                        choices=[
                            ("warm", "Warm"),
                            ("cool", "Cool"),
                            ("cold", "Cold"),
                            ("hot", "Hot"),
                        ],
                        max_length=20,
                    ),
                ),
            ],
            options={},
            bases=("trainerlab.abcevent",),
        ),
    ]
