# Generated by Django 6.0.3 on 2026-03-16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trainerlab", "0012_alter_intervention_intervention_type_pulseassessment"),
        ("simcore", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DebriefAnnotation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "learning_objective",
                    models.CharField(
                        choices=[
                            ("assessment", "Patient Assessment"),
                            ("hemorrhage_control", "Hemorrhage Control"),
                            ("airway", "Airway Management"),
                            ("breathing", "Breathing / Respiration"),
                            ("circulation", "Circulation / Shock"),
                            ("hypothermia", "Hypothermia Prevention"),
                            ("communication", "Communication / Reporting"),
                            ("triage", "Triage Decision"),
                            ("intervention", "Intervention Technique"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=32,
                    ),
                ),
                ("observation_text", models.TextField(max_length=2000)),
                (
                    "outcome",
                    models.CharField(
                        choices=[
                            ("correct", "Correct"),
                            ("incorrect", "Incorrect"),
                            ("missed", "Missed"),
                            ("improvised", "Improvised"),
                            ("pending", "Pending / Unscored"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                (
                    "linked_event_id",
                    models.IntegerField(blank=True, null=True),
                ),
                (
                    "elapsed_seconds_at",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="debrief_annotations",
                        to="trainerlab.trainersession",
                    ),
                ),
                (
                    "simulation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="debrief_annotations",
                        to="simcore.simulation",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="trainerlab_debrief_annotations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
                "indexes": [
                    models.Index(
                        fields=["session", "created_at"],
                        name="idx_debrief_annotation_session",
                    ),
                    models.Index(
                        fields=["simulation", "created_at"],
                        name="idx_debrief_annotation_sim",
                    ),
                ],
            },
        ),
    ]
