# Generated by Django 6.0.3 on 2026-03-16 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trainerlab", "0012_debriefannotation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="intervention",
            name="intervention_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("tourniquet", "Tourniquet"),
                    ("wound_packing", "Wound Packing"),
                    ("pressure_dressing", "Pressure Dressing"),
                    ("npa", "Nasopharyngeal Airway"),
                    ("opa", "Oropharyngeal Airway"),
                    ("needle_decompression", "Needle Decompression"),
                    ("surgical_cric", "Surgical Cricothyrotomy"),
                    ("junctional_tourniquet", "Junctional Tourniquet"),
                    ("hemostatic_agent", "Hemostatic Agent"),
                    ("pelvic_binder", "Pelvic Binder"),
                    ("iv_access", "IV Access"),
                    ("io_access", "IO Access"),
                    ("fluid_resuscitation", "Fluid Resuscitation"),
                    ("blood_transfusion", "Blood Transfusion / WBCT"),
                    ("advanced_airway", "Advanced Airway"),
                    ("chest_tube", "Chest Tube / Finger Thoracostomy"),
                ],
                db_index=True,
                default="",
                max_length=64,
            ),
        ),
    ]
