# Generated by Django 6.0.3 on 2026-03-17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trainerlab", "0013_debriefannotation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="injury",
            name="injury_description",
            field=models.CharField(max_length=500),
        ),
    ]
