# Generated by Django 6.0.3 on 2026-03-17 20:51

import django.db.models.deletion
from django.db import migrations, models
from slugify import slugify


def _normalized_slug(value: str) -> str:
    return slugify(value or "", separator="_")


def _normalized_code(value: str) -> str:
    return _normalized_slug(value).upper()


def _derive_laterality(value: str) -> str:
    normalized = (value or "").upper()
    if "LEFT" in normalized or normalized.startswith("L"):
        return "left"
    if "RIGHT" in normalized or normalized.startswith("R"):
        return "right"
    return ""


def _backfill_trainerlab_domain_fields(apps, _schema_editor):
    Injury = apps.get_model("trainerlab", "Injury")
    Illness = apps.get_model("trainerlab", "Illness")
    Problem = apps.get_model("trainerlab", "Problem")
    Intervention = apps.get_model("trainerlab", "Intervention")

    injury_location_labels = dict(Injury._meta.get_field("injury_location").choices)
    injury_kind_labels = dict(Injury._meta.get_field("injury_kind").choices)

    for injury in Injury.objects.all().iterator():
        injury_kind_label = injury_kind_labels.get(injury.injury_kind, injury.injury_kind)
        location_label = injury_location_labels.get(injury.injury_location, injury.injury_location)
        injury.kind = injury.kind or _normalized_slug(injury_kind_label)
        injury.code = injury.code or injury.injury_kind
        injury.slug = injury.slug or _normalized_slug(injury.kind or injury.code)
        injury.title = injury.title or injury.injury_description or injury_kind_label
        injury.display_name = injury.display_name or injury.title
        injury.description = injury.description or injury.injury_description or ""
        injury.anatomical_location = injury.anatomical_location or location_label
        injury.laterality = injury.laterality or _derive_laterality(injury.anatomical_location)
        injury.save(
            update_fields=[
                "kind",
                "code",
                "slug",
                "title",
                "display_name",
                "description",
                "anatomical_location",
                "laterality",
            ]
        )

    for illness in Illness.objects.all().iterator():
        illness.kind = illness.kind or _normalized_slug(illness.name)
        illness.code = illness.code or _normalized_code(illness.name)
        illness.slug = illness.slug or _normalized_slug(illness.kind or illness.name)
        illness.title = illness.title or illness.name
        illness.display_name = illness.display_name or illness.title
        illness.save(update_fields=["kind", "code", "slug", "title", "display_name"])

    for problem in Problem.objects.select_related("cause_injury", "cause_illness").all().iterator():
        cause = problem.cause_injury or problem.cause_illness
        if problem.march_category == "M":
            canonical_kind = "hemorrhage"
        elif problem.march_category == "A":
            canonical_kind = "airway_obstruction"
        elif problem.march_category == "R":
            canonical_kind = "respiratory_distress"
        elif problem.cause_injury_id:
            canonical_kind = _normalized_slug(
                problem.cause_injury.injury_kind if problem.cause_injury else problem.problem_kind
            )
        elif problem.cause_illness_id:
            canonical_kind = _normalized_slug(problem.cause_illness.name if problem.cause_illness else "illness_problem")
        else:
            canonical_kind = _normalized_slug(problem.problem_kind or "clinical_problem")

        if problem.is_resolved:
            status = "resolved"
            treated_at = problem.timestamp
            controlled_at = problem.timestamp
            resolved_at = problem.timestamp
        elif problem.is_treated:
            status = "treated"
            treated_at = problem.timestamp
            controlled_at = None
            resolved_at = None
        else:
            status = "active"
            treated_at = None
            controlled_at = None
            resolved_at = None

        title = problem.title or problem.description or ""
        if not title and problem.cause_injury_id and cause is not None:
            title = cause.injury_description
        if not title and problem.cause_illness_id and cause is not None:
            title = cause.name
        if not title:
            title = "Clinical problem"

        problem.kind = problem.kind or canonical_kind
        problem.code = problem.code or canonical_kind
        problem.slug = problem.slug or _normalized_slug(problem.kind or problem.code)
        problem.title = title
        problem.display_name = problem.display_name or title
        problem.anatomical_location = problem.anatomical_location or getattr(
            cause, "anatomical_location", ""
        )
        problem.laterality = problem.laterality or getattr(cause, "laterality", "")
        problem.status = problem.status or status
        problem.treated_at = problem.treated_at or treated_at
        problem.controlled_at = problem.controlled_at or controlled_at
        problem.resolved_at = problem.resolved_at or resolved_at
        problem.save(
            update_fields=[
                "kind",
                "code",
                "slug",
                "title",
                "display_name",
                "anatomical_location",
                "laterality",
                "status",
                "treated_at",
                "controlled_at",
                "resolved_at",
            ]
        )

    role_map = {
        "trainee": "user",
        "instructor": "instructor",
        "system": "system",
        "ai": "system",
    }
    for intervention in Intervention.objects.all().iterator():
        intervention.initiated_by_type = role_map.get(
            intervention.performed_by_role,
            intervention.initiated_by_type,
        )
        intervention.save(update_fields=["initiated_by_type"])


def _noop_reverse(_apps, _schema_editor):
    return None


class Migration(migrations.Migration):

    dependencies = [
        ('simcore', '0005_simulation_feedback_retry_count_and_more'),
        ('trainerlab', '0015_remove_abcevent_polymorphism'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecommendedIntervention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('ai', 'AI'), ('instructor', 'Instructor'), ('system', 'System')], default='system', max_length=16)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('kind', models.CharField(db_index=True, max_length=64)),
                ('code', models.CharField(db_index=True, max_length=64)),
                ('slug', models.SlugField(blank=True, default='', max_length=80)),
                ('title', models.CharField(max_length=120)),
                ('display_name', models.CharField(blank=True, default='', max_length=120)),
                ('description', models.TextField(blank=True, default='')),
                ('recommendation_source', models.CharField(choices=[('ai', 'AI'), ('rules', 'Rules'), ('merged', 'Merged')], default='ai', max_length=16)),
                ('validation_status', models.CharField(choices=[('accepted', 'Accepted'), ('normalized', 'Normalized'), ('downgraded', 'Downgraded'), ('rejected', 'Rejected')], db_index=True, default='accepted', max_length=16)),
                ('normalized_kind', models.CharField(blank=True, default='', max_length=64)),
                ('normalized_code', models.CharField(blank=True, default='', max_length=64)),
                ('rationale', models.TextField(blank=True, default='')),
                ('priority', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('site_code', models.CharField(blank=True, default='', max_length=64)),
                ('site_label', models.CharField(blank=True, default='', max_length=120)),
                ('contraindications_json', models.JSONField(blank=True, default=list)),
                ('warnings_json', models.JSONField(blank=True, default=list)),
                ('metadata_json', models.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.AddField(
            model_name='illness',
            name='anatomical_location',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='illness',
            name='code',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='illness',
            name='display_name',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='illness',
            name='kind',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='illness',
            name='laterality',
            field=models.CharField(blank=True, default='', max_length=16),
        ),
        migrations.AddField(
            model_name='illness',
            name='metadata_json',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='illness',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=80),
        ),
        migrations.AddField(
            model_name='illness',
            name='title',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='injury',
            name='anatomical_location',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='injury',
            name='code',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='injury',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='injury',
            name='display_name',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='injury',
            name='kind',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='injury',
            name='laterality',
            field=models.CharField(blank=True, default='', max_length=16),
        ),
        migrations.AddField(
            model_name='injury',
            name='metadata_json',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='injury',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=80),
        ),
        migrations.AddField(
            model_name='injury',
            name='title',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='intervention',
            name='initiated_by_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='intervention',
            name='initiated_by_type',
            field=models.CharField(choices=[('user', 'User'), ('instructor', 'Instructor'), ('system', 'System')], db_index=True, default='user', max_length=16),
        ),
        migrations.AddField(
            model_name='problem',
            name='anatomical_location',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='problem',
            name='code',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='problem',
            name='controlled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='problem',
            name='display_name',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='problem',
            name='kind',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='problem',
            name='laterality',
            field=models.CharField(blank=True, default='', max_length=16),
        ),
        migrations.AddField(
            model_name='problem',
            name='metadata_json',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='problem',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='problem',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=80),
        ),
        migrations.AddField(
            model_name='problem',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('treated', 'Treated'), ('controlled', 'Controlled'), ('resolved', 'Resolved')], db_index=True, default='active', max_length=16),
        ),
        migrations.AddField(
            model_name='problem',
            name='title',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='problem',
            name='treated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='intervention',
            name='intervention_type',
            field=models.CharField(blank=True, choices=[('tourniquet', 'Tourniquet'), ('wound_packing', 'Wound Packing'), ('pressure_dressing', 'Pressure Dressing'), ('npa', 'Nasopharyngeal Airway'), ('opa', 'Oropharyngeal Airway'), ('chest_seal', 'Chest Seal'), ('needle_decompression', 'Needle Decompression'), ('surgical_cric', 'Surgical Cricothyrotomy'), ('junctional_tourniquet', 'Junctional Tourniquet'), ('hemostatic_agent', 'Hemostatic Agent'), ('pelvic_binder', 'Pelvic Binder'), ('iv_access', 'IV Access'), ('io_access', 'IO Access'), ('fluid_resuscitation', 'Fluid Resuscitation'), ('blood_transfusion', 'Blood Transfusion / WBCT'), ('advanced_airway', 'Advanced Airway'), ('chest_tube', 'Chest Tube / Finger Thoracostomy'), ('antibiotics', 'Antibiotics')], db_index=True, default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='intervention',
            name='performed_by_role',
            field=models.CharField(choices=[('trainee', 'Trainee'), ('instructor', 'Instructor'), ('system', 'System')], default='trainee', max_length=16),
        ),
        migrations.AlterField(
            model_name='problem',
            name='problem_kind',
            field=models.CharField(choices=[('injury', 'Injury'), ('illness', 'Illness'), ('other', 'Other')], db_index=True, default='other', help_text='Deprecated direct-cause classification; prefer kind/code for problem identity.', max_length=16),
        ),
        migrations.AddIndex(
            model_name='problem',
            index=models.Index(fields=['simulation', 'status'], name='idx_problem_sim_status'),
        ),
        migrations.AddIndex(
            model_name='problem',
            index=models.Index(fields=['simulation', 'kind'], name='idx_problem_sim_kind'),
        ),
        migrations.AddField(
            model_name='recommendedintervention',
            name='simulation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='simcore.simulation'),
        ),
        migrations.AddField(
            model_name='recommendedintervention',
            name='supersedes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='superseded_by', to='trainerlab.recommendedintervention'),
        ),
        migrations.AddField(
            model_name='recommendedintervention',
            name='target_illness',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recommended_interventions', to='trainerlab.illness'),
        ),
        migrations.AddField(
            model_name='recommendedintervention',
            name='target_injury',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recommended_interventions', to='trainerlab.injury'),
        ),
        migrations.AddField(
            model_name='recommendedintervention',
            name='target_problem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommended_interventions', to='trainerlab.problem'),
        ),
        migrations.AddIndex(
            model_name='recommendedintervention',
            index=models.Index(fields=['simulation', 'validation_status'], name='idx_reco_sim_validation'),
        ),
        migrations.AddIndex(
            model_name='recommendedintervention',
            index=models.Index(fields=['target_problem'], name='idx_reco_target_problem'),
        ),
        migrations.RunPython(_backfill_trainerlab_domain_fields, _noop_reverse),
    ]
