# Generated by Django 6.0.3 on 2026-03-18 00:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simcore', '0005_simulation_feedback_retry_count_and_more'),
        ('trainerlab', '0016_recommendedintervention_illness_anatomical_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='intervention',
            name='adjudication_reason',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='intervention',
            name='adjudication_rule_id',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='intervention',
            name='target_problem_current_status',
            field=models.CharField(blank=True, default='', max_length=16),
        ),
        migrations.AddField(
            model_name='intervention',
            name='target_problem_previous_status',
            field=models.CharField(blank=True, default='', max_length=16),
        ),
        migrations.AddField(
            model_name='problem',
            name='adjudication_reason',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='problem',
            name='adjudication_rule_id',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='problem',
            name='parent_problem',
            field=models.ForeignKey(blank=True, help_text='Optional parent problem for derived/systemic progression while preserving the direct cause relationship.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='derived_problems', to='trainerlab.problem'),
        ),
        migrations.AddField(
            model_name='problem',
            name='previous_status',
            field=models.CharField(blank=True, default='', max_length=16),
        ),
        migrations.AddField(
            model_name='problem',
            name='triggering_intervention',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triggered_problem_updates', to='trainerlab.intervention'),
        ),
        migrations.CreateModel(
            name='AssessmentFinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('ai', 'AI'), ('instructor', 'Instructor'), ('system', 'System')], default='system', max_length=16)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('kind', models.CharField(db_index=True, max_length=64)),
                ('code', models.CharField(db_index=True, max_length=64)),
                ('slug', models.SlugField(blank=True, default='', max_length=80)),
                ('title', models.CharField(max_length=120)),
                ('display_name', models.CharField(blank=True, default='', max_length=120)),
                ('description', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('present', 'Present'), ('stable', 'Stable'), ('improving', 'Improving'), ('worsening', 'Worsening')], db_index=True, default='present', max_length=16)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('moderate', 'Moderate'), ('high', 'High'), ('critical', 'Critical')], default='moderate', max_length=16)),
                ('anatomical_location', models.CharField(blank=True, default='', max_length=120)),
                ('laterality', models.CharField(blank=True, default='', max_length=16)),
                ('metadata_json', models.JSONField(blank=True, default=dict)),
                ('simulation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='simcore.simulation')),
                ('supersedes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='superseded_by', to='trainerlab.assessmentfinding')),
                ('target_problem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assessment_findings', to='trainerlab.problem')),
            ],
            options={
                'indexes': [models.Index(fields=['simulation', 'kind'], name='idx_finding_sim_kind'), models.Index(fields=['target_problem'], name='idx_finding_problem')],
            },
        ),
        migrations.CreateModel(
            name='DiagnosticResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('ai', 'AI'), ('instructor', 'Instructor'), ('system', 'System')], default='system', max_length=16)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('kind', models.CharField(db_index=True, max_length=64)),
                ('code', models.CharField(db_index=True, max_length=64)),
                ('slug', models.SlugField(blank=True, default='', max_length=80)),
                ('title', models.CharField(max_length=120)),
                ('display_name', models.CharField(blank=True, default='', max_length=120)),
                ('description', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('available', 'Available'), ('reviewed', 'Reviewed')], db_index=True, default='pending', max_length=16)),
                ('value_text', models.CharField(blank=True, default='', max_length=255)),
                ('metadata_json', models.JSONField(blank=True, default=dict)),
                ('simulation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='simcore.simulation')),
                ('supersedes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='superseded_by', to='trainerlab.diagnosticresult')),
                ('target_problem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diagnostic_results', to='trainerlab.problem')),
            ],
            options={
                'indexes': [models.Index(fields=['simulation', 'kind'], name='idx_diag_sim_kind'), models.Index(fields=['target_problem'], name='idx_diag_problem')],
            },
        ),
        migrations.CreateModel(
            name='DispositionState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('ai', 'AI'), ('instructor', 'Instructor'), ('system', 'System')], default='system', max_length=16)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('hold', 'Hold'), ('ready', 'Ready'), ('en_route', 'En Route'), ('delayed', 'Delayed'), ('complete', 'Complete')], db_index=True, default='hold', max_length=16)),
                ('transport_mode', models.CharField(blank=True, default='', max_length=64)),
                ('destination', models.CharField(blank=True, default='', max_length=120)),
                ('eta_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('handoff_ready', models.BooleanField(default=False)),
                ('scene_constraints_json', models.JSONField(blank=True, default=list)),
                ('metadata_json', models.JSONField(blank=True, default=dict)),
                ('simulation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='simcore.simulation')),
                ('supersedes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='superseded_by', to='trainerlab.dispositionstate')),
            ],
            options={
                'indexes': [models.Index(fields=['simulation', 'status'], name='idx_dispo_sim_status')],
            },
        ),
        migrations.CreateModel(
            name='RecommendationEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('ai', 'AI'), ('instructor', 'Instructor'), ('system', 'System')], default='system', max_length=16)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('raw_kind', models.CharField(blank=True, default='', max_length=120)),
                ('raw_title', models.CharField(blank=True, default='', max_length=120)),
                ('raw_site', models.CharField(blank=True, default='', max_length=120)),
                ('normalized_kind', models.CharField(blank=True, default='', max_length=64)),
                ('normalized_code', models.CharField(blank=True, default='', max_length=64)),
                ('title', models.CharField(blank=True, default='', max_length=120)),
                ('recommendation_source', models.CharField(choices=[('ai', 'AI'), ('rules', 'Rules'), ('merged', 'Merged')], default='ai', max_length=16)),
                ('validation_status', models.CharField(choices=[('accepted', 'Accepted'), ('normalized', 'Normalized'), ('downgraded', 'Downgraded'), ('rejected', 'Rejected')], db_index=True, default='accepted', max_length=16)),
                ('rationale', models.TextField(blank=True, default='')),
                ('priority', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('warnings_json', models.JSONField(blank=True, default=list)),
                ('contraindications_json', models.JSONField(blank=True, default=list)),
                ('rejection_reason', models.CharField(blank=True, default='', max_length=255)),
                ('metadata_json', models.JSONField(blank=True, default=dict)),
                ('recommendation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evaluations', to='trainerlab.recommendedintervention')),
                ('simulation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='simcore.simulation')),
                ('target_illness', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recommendation_evaluations', to='trainerlab.illness')),
                ('target_injury', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recommendation_evaluations', to='trainerlab.injury')),
                ('target_problem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recommendation_evaluations', to='trainerlab.problem')),
            ],
            options={
                'indexes': [models.Index(fields=['simulation', 'validation_status'], name='idx_reval_sim_status'), models.Index(fields=['target_problem'], name='idx_reval_problem')],
            },
        ),
        migrations.CreateModel(
            name='ResourceState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('ai', 'AI'), ('instructor', 'Instructor'), ('system', 'System')], default='system', max_length=16)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('kind', models.CharField(db_index=True, max_length=64)),
                ('code', models.CharField(db_index=True, max_length=64)),
                ('slug', models.SlugField(blank=True, default='', max_length=80)),
                ('title', models.CharField(max_length=120)),
                ('display_name', models.CharField(blank=True, default='', max_length=120)),
                ('status', models.CharField(choices=[('available', 'Available'), ('limited', 'Limited'), ('depleted', 'Depleted'), ('unavailable', 'Unavailable')], db_index=True, default='available', max_length=16)),
                ('quantity_available', models.IntegerField(default=0)),
                ('quantity_unit', models.CharField(blank=True, default='', max_length=32)),
                ('description', models.TextField(blank=True, default='')),
                ('metadata_json', models.JSONField(blank=True, default=dict)),
                ('simulation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='simcore.simulation')),
                ('supersedes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='superseded_by', to='trainerlab.resourcestate')),
            ],
            options={
                'indexes': [models.Index(fields=['simulation', 'code'], name='idx_resource_sim_code')],
            },
        ),
    ]
