# Generated by Django 6.0.3 on 2026-03-20 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainerlab', '0017_intervention_adjudication_reason_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainersession',
            name='status',
            field=models.CharField(choices=[('seeding', 'Seeding'), ('seeded', 'Seeded'), ('running', 'Running'), ('paused', 'Paused'), ('completed', 'Completed'), ('failed', 'Failed')], default='seeded', max_length=16),
        ),
    ]
