# Generated by Django 6.0.3 on 2026-04-03 15:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orchestrai_django', '0001_initial'),
        ('simcore', '0008_backfill_simulation_accounts'),
        ('trainerlab', '0018_alter_trainersession_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientStatusState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('ai', 'AI'), ('instructor', 'Instructor'), ('system', 'System')], default='system', max_length=16)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('avpu', models.CharField(blank=True, default='', max_length=24)),
                ('respiratory_distress', models.BooleanField(default=False)),
                ('hemodynamic_instability', models.BooleanField(default=False)),
                ('impending_pneumothorax', models.BooleanField(default=False)),
                ('tension_pneumothorax', models.BooleanField(default=False)),
                ('narrative', models.TextField(blank=True, default='')),
                ('teaching_flags', models.JSONField(blank=True, default=list)),
                ('simulation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='simcore.simulation')),
                ('supersedes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='superseded_by', to='trainerlab.patientstatusstate')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TrainerAgentViewModelRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_revision', models.PositiveIntegerField(default=0)),
                ('correlation_id', models.CharField(blank=True, default='', max_length=100)),
                ('builder_version', models.CharField(default='v1', max_length=32)),
                ('schema_version', models.CharField(default='v1', max_length=32)),
                ('payload_json', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('service_call', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trainer_agent_view_model_records', to='orchestrai_django.servicecall')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_view_model_records', to='trainerlab.trainersession')),
            ],
            options={
                'indexes': [models.Index(fields=['session', 'created_at'], name='idx_tl_agent_vm_session'), models.Index(fields=['session', 'state_revision'], name='idx_tl_agent_vm_revision'), models.Index(fields=['correlation_id'], name='idx_tl_agent_vm_corr')],
            },
        ),
    ]
