# Generated by Django 6.0.3 on 2026-04-03 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainerlab', '0019_patientstatusstate_traineragentviewmodelrecord'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientstatusstate',
            name='narrative',
        ),
        migrations.RemoveField(
            model_name='patientstatusstate',
            name='teaching_flags',
        ),
    ]
