services:
  sim-works:
    image: ghcr.io/jackfruitco/SimWorks:${SERVER_IMAGE_TAG:-latest}
    env_file:
      - stack.env
    expose:
      - 8000
    hostname: 'server'
    volumes:
      - static-vol:/app/static
      - media-vol:/app/media
    command: ["/app/docker/entrypoint.prod.sh"]
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - SimWorksNet
    depends_on:
      sim-works-db:
        condition: service_healthy

  sim-works-db:
    image: postgres:${DB_IMAGE_TAG:-17.2-alpine}
    restart: always
    user: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    env_file:
      - stack.env
    environment:
      POSTGRES_DB: ${DB_NAME:-AppDatabase}
      POSTGRES_USER: ${DB_USER:-appuser}
      POSTGRES_PASSWORD: ${DB_PASSWORD:?password not set!}
      POSTGRES_HOST: ${DB_HOST:-db}
      POSTGRES_PORT: ${DB_PORT:-5432}
    networks:
      - SimWorksNet
    expose:
      - '${DB_PORT:-5432}'
    hostname: 'db'
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5

  sim-works-nginx:
    image: nginx:${PROXY_IMAGE_TAG:-latest}
    ports:
      - "80:80"
    env_file:
      - stack.env
    volumes:
      - ../nginx/custom-nginx.conf:/etc/nginx/conf.d/default.conf
      - static-vol:/app/static
      - media-vol:/app/media
    depends_on:
      - sim-works
    networks:
      - SimWorksNet

  sim-works-redis:
    image: redis:${REDIS_IMAGE_TAG:-7.4.2-alpine}
    command: redis-server --requirepass ${REDIS_PASSWORD:?password not set!}
    container_name: ${REDIS_HOSTNAME:-redis}
    hostname: ${REDIS_HOSTNAME:-redis}
    env_file:
      - stack.env
    networks:
      - SimWorksNet
    expose:
      - '${REDIS_PORT:-6379}'

volumes:
  db-data:
  static-vol:
  media-vol:
networks:
  SimWorksNet:
    driver: bridge
