# Generated by Django 6.0.4 on 2026-04-26 23:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('provider_type', models.CharField(choices=[('stripe', 'Stripe'), ('apple', 'Apple'), ('manual', 'Manual'), ('internal', 'Internal')], max_length=20)),
                ('provider_customer_id', models.CharField(blank=True, default='', max_length=255)),
                ('tax_exempt_status', models.CharField(blank=True, default='', max_length=50)),
                ('billing_email', models.EmailField(blank=True, default='', max_length=254)),
                ('country_code', models.CharField(blank=True, default='', max_length=2)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billing_accounts', to='accounts.account')),
            ],
            options={
                'ordering': ('account_id', 'provider_type', 'id'),
            },
        ),
        migrations.CreateModel(
            name='Entitlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('source_type', models.CharField(choices=[('subscription', 'Subscription'), ('membership', 'Membership'), ('grant', 'Grant'), ('manual', 'Manual'), ('promo', 'Promo')], max_length=32)),
                ('source_ref', models.CharField(max_length=255)),
                ('scope_type', models.CharField(choices=[('account', 'Account'), ('user', 'User')], max_length=20)),
                ('product_code', models.CharField(max_length=100)),
                ('feature_code', models.CharField(blank=True, default='', max_length=100)),
                ('limit_code', models.CharField(blank=True, default='', max_length=100)),
                ('limit_value', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('scheduled', 'Scheduled'), ('expired', 'Expired'), ('revoked', 'Revoked')], default='active', max_length=20)),
                ('portable_across_accounts', models.BooleanField(default=False)),
                ('starts_at', models.DateTimeField(blank=True, null=True)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entitlements', to='accounts.account')),
                ('subject_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entitlements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('account_id', 'product_code', 'feature_code', 'limit_code', 'id'),
            },
        ),
        migrations.CreateModel(
            name='SeatAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_code', models.CharField(max_length=100)),
                ('seat_limit', models.PositiveIntegerField()),
                ('seat_used', models.PositiveIntegerField(default=0)),
                ('effective_from', models.DateTimeField()),
                ('effective_to', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seat_allocations', to='accounts.account')),
            ],
            options={
                'ordering': ('account_id', 'product_code', '-effective_from'),
            },
        ),
        migrations.CreateModel(
            name='SeatAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_code', models.CharField(max_length=100)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seat_assignments', to='accounts.account')),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_seats', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seat_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('account_id', 'product_code', '-assigned_at'),
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('provider_type', models.CharField(choices=[('stripe', 'Stripe'), ('apple', 'Apple'), ('manual', 'Manual'), ('internal', 'Internal')], max_length=20)),
                ('provider_subscription_id', models.CharField(blank=True, default='', max_length=255)),
                ('provider_original_transaction_id', models.CharField(blank=True, default='', max_length=255)),
                ('plan_code', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('trialing', 'Trialing'), ('active', 'Active'), ('grace_period', 'Grace Period'), ('past_due', 'Past Due'), ('canceled', 'Canceled'), ('expired', 'Expired'), ('paused', 'Paused')], max_length=32)),
                ('starts_at', models.DateTimeField(blank=True, null=True)),
                ('current_period_start', models.DateTimeField(blank=True, null=True)),
                ('current_period_end', models.DateTimeField(blank=True, null=True)),
                ('cancel_at_period_end', models.BooleanField(default=False)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('provider_payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='accounts.account')),
                ('billing_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscriptions', to='billing.billingaccount')),
            ],
            options={
                'ordering': ('account_id', '-updated_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='WebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_type', models.CharField(choices=[('stripe', 'Stripe'), ('apple', 'Apple'), ('manual', 'Manual'), ('internal', 'Internal')], max_length=20)),
                ('event_id', models.CharField(max_length=255)),
                ('event_type', models.CharField(max_length=255)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processed', 'Processed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('request_headers', models.JSONField(blank=True, default=dict)),
                ('processing_error', models.TextField(blank=True, default='')),
            ],
            options={
                'ordering': ('-received_at', '-id'),
                'indexes': [models.Index(fields=['provider_type', 'status'], name='idx_webhook_provider_status'), models.Index(fields=['event_type', 'received_at'], name='idx_webhook_type_received')],
                'constraints': [models.UniqueConstraint(fields=('provider_type', 'event_id'), name='uniq_webhook_event_provider_event')],
            },
        ),
        migrations.AddIndex(
            model_name='billingaccount',
            index=models.Index(fields=['account', 'provider_type'], name='idx_billing_account_provider'),
        ),
        migrations.AddIndex(
            model_name='billingaccount',
            index=models.Index(fields=['billing_email'], name='idx_billing_account_email'),
        ),
        migrations.AddConstraint(
            model_name='billingaccount',
            constraint=models.UniqueConstraint(condition=models.Q(('provider_customer_id__gt', '')), fields=('provider_type', 'provider_customer_id'), name='uniq_billing_account_provider_customer'),
        ),
        migrations.AddIndex(
            model_name='entitlement',
            index=models.Index(fields=['account', 'status', 'product_code'], name='idx_entitlement_product'),
        ),
        migrations.AddIndex(
            model_name='entitlement',
            index=models.Index(fields=['subject_user', 'status', 'product_code'], name='idx_entitlement_user_product'),
        ),
        migrations.AddIndex(
            model_name='entitlement',
            index=models.Index(fields=['source_type', 'source_ref'], name='idx_entitlement_source'),
        ),
        migrations.AddConstraint(
            model_name='entitlement',
            constraint=models.UniqueConstraint(condition=models.Q(('subject_user__isnull', True)), fields=('account', 'source_type', 'source_ref', 'scope_type', 'product_code', 'feature_code', 'limit_code'), name='uniq_entitlement_source_account_scope_code'),
        ),
        migrations.AddConstraint(
            model_name='entitlement',
            constraint=models.UniqueConstraint(condition=models.Q(('subject_user__isnull', False)), fields=('account', 'source_type', 'source_ref', 'scope_type', 'subject_user', 'product_code', 'feature_code', 'limit_code'), name='uniq_entitlement_source_user_scope_code'),
        ),
        migrations.AddIndex(
            model_name='seatallocation',
            index=models.Index(fields=['account', 'product_code'], name='idx_seat_allocation_product'),
        ),
        migrations.AddIndex(
            model_name='seatassignment',
            index=models.Index(fields=['account', 'product_code'], name='idx_seat_assignment_product'),
        ),
        migrations.AddIndex(
            model_name='seatassignment',
            index=models.Index(fields=['user', 'product_code'], name='idx_seat_assignment_user'),
        ),
        migrations.AddConstraint(
            model_name='seatassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('ended_at__isnull', True), ('user__isnull', False)), fields=('account', 'user', 'product_code'), name='uniq_open_seat_assignment'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['account', 'status'], name='idx_sub_account_status'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['plan_code', 'status'], name='idx_subscription_plan_status'),
        ),
        migrations.AddConstraint(
            model_name='subscription',
            constraint=models.UniqueConstraint(condition=models.Q(('provider_subscription_id__gt', '')), fields=('provider_type', 'provider_subscription_id'), name='uniq_subscription_provider_id'),
        ),
        migrations.AddConstraint(
            model_name='subscription',
            constraint=models.UniqueConstraint(condition=models.Q(('provider_original_transaction_id__gt', '')), fields=('provider_type', 'provider_original_transaction_id'), name='uniq_subscription_original_txn'),
        ),
    ]
