# Generated by Django 6.0.3 on 2026-03-23 14:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_account_user_active_account_accountauditevent_and_more'),
        ('billing', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='entitlement',
            name='uniq_entitlement_source_scope_code',
        ),
        migrations.AddConstraint(
            model_name='entitlement',
            constraint=models.UniqueConstraint(condition=models.Q(('subject_user__isnull', True)), fields=('account', 'source_type', 'source_ref', 'scope_type', 'product_code', 'feature_code', 'limit_code'), name='uniq_entitlement_source_account_scope_code'),
        ),
        migrations.AddConstraint(
            model_name='entitlement',
            constraint=models.UniqueConstraint(condition=models.Q(('subject_user__isnull', False)), fields=('account', 'source_type', 'source_ref', 'scope_type', 'subject_user', 'product_code', 'feature_code', 'limit_code'), name='uniq_entitlement_source_user_scope_code'),
        ),
    ]
