# Generated by Codex on 2026-03-23

from django.db import migrations


def forwards(apps, schema_editor):
    Account = apps.get_model("accounts", "Account")
    LabMembership = apps.get_model("accounts", "LabMembership")
    Entitlement = apps.get_model("billing", "Entitlement")
    db_alias = schema_editor.connection.alias
    account_map = dict(
        Account.objects.using(db_alias)
        .filter(account_type="personal")
        .values_list("owner_user_id", "id")
    )

    memberships = (
        LabMembership.objects.using(db_alias)
        .filter(is_active=True, revoked_at__isnull=True)
        .select_related("lab")
        .order_by("id")
    )
    for membership in memberships.iterator(chunk_size=250):
        account_id = account_map.get(membership.user_id)
        if account_id is None:
            continue

        base_defaults = {
            "status": "active",
            "portable_across_accounts": True,
            "starts_at": membership.granted_at,
            "ends_at": None,
            "metadata": {
                "legacy_lab_membership_id": membership.id,
                "legacy_access_level": membership.access_level,
            },
        }
        Entitlement.objects.using(db_alias).update_or_create(
            account_id=account_id,
            source_type="membership",
            source_ref=f"lab_membership:{membership.id}",
            scope_type="user",
            subject_user_id=membership.user_id,
            product_code=membership.lab.slug,
            feature_code="",
            limit_code="",
            defaults=base_defaults,
        )

        if membership.access_level in {"instructor", "admin"}:
            Entitlement.objects.using(db_alias).update_or_create(
                account_id=account_id,
                source_type="membership",
                source_ref=f"lab_membership:{membership.id}",
                scope_type="user",
                subject_user_id=membership.user_id,
                product_code=membership.lab.slug,
                feature_code="instructor_tools",
                limit_code="",
                defaults=base_defaults,
            )


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ("accounts", "0004_backfill_personal_accounts"),
        ("billing", "0002_remove_entitlement_uniq_entitlement_source_scope_code_and_more"),
    ]

    operations = [
        migrations.RunPython(forwards, migrations.RunPython.noop),
    ]
