# Generated by Codex on 2026-03-24

from __future__ import annotations

from django.db import migrations

CANONICAL_PRODUCT_CODES = {
    "chatlab_go",
    "chatlab_plus",
    "trainerlab_go",
    "trainerlab_plus",
    "medsim_one",
    "medsim_one_plus",
}

PRODUCT_CODE_MAP = {
    "chatlab": "chatlab_go",
    "trainerlab": "trainerlab_go",
    "com.jackfruitco.medsim.chatlab.go.monthly": "chatlab_go",
    "com.jackfruitco.medsim.chatlab.plus.monthly": "chatlab_plus",
    "com.jackfruitco.medsim.individual.plus.monthly": "chatlab_plus",
    "com.jackfruitco.medsim.trainerlab.go.monthly": "trainerlab_go",
    "com.jackfruitco.medsim.trainerlab.plus.monthly": "trainerlab_plus",
    "com.jackfruitco.medsim.one.monthly": "medsim_one",
    "com.jackfruitco.medsim.one.plus.monthly": "medsim_one_plus",
    "price_chatlab_go_monthly": "chatlab_go",
    "chatlab_go_monthly": "chatlab_go",
    "price_chatlab_plus_monthly": "chatlab_plus",
    "chatlab_plus_monthly": "chatlab_plus",
    "price_trainerlab_go_monthly": "trainerlab_go",
    "trainerlab_go_monthly": "trainerlab_go",
    "price_trainerlab_plus_monthly": "trainerlab_plus",
    "trainerlab_plus_monthly": "trainerlab_plus",
    "price_medsim_one_monthly": "medsim_one",
    "medsim_one_monthly": "medsim_one",
    "price_medsim_one_plus_monthly": "medsim_one_plus",
    "medsim_one_plus_monthly": "medsim_one_plus",
}


def _normalize_entitlements(apps, db_alias: str):
    Entitlement = apps.get_model("billing", "Entitlement")

    deleted_count, _ = Entitlement.objects.using(db_alias).exclude(
        feature_code="",
        limit_code="",
    ).delete()
    if deleted_count:
        print(
            "[billing] Deleted",
            deleted_count,
            "legacy feature/limit entitlement rows during product-code normalization.",
        )

    queryset = Entitlement.objects.using(db_alias).filter(product_code__in=PRODUCT_CODE_MAP)
    for entitlement in queryset.iterator(chunk_size=250):
        canonical_product_code = PRODUCT_CODE_MAP[entitlement.product_code]
        duplicate = Entitlement.objects.using(db_alias).filter(
            account_id=entitlement.account_id,
            source_type=entitlement.source_type,
            source_ref=entitlement.source_ref,
            scope_type=entitlement.scope_type,
            subject_user_id=entitlement.subject_user_id,
            product_code=canonical_product_code,
            feature_code=entitlement.feature_code,
            limit_code=entitlement.limit_code,
        )
        duplicate = duplicate.exclude(pk=entitlement.pk).first()
        if duplicate is not None:
            entitlement.delete()
            continue
        entitlement.product_code = canonical_product_code
        entitlement.save(update_fields=["product_code"])

    remaining = sorted(
        {
            value
            for value in Entitlement.objects.using(db_alias)
            .values_list("product_code", flat=True)
            .distinct()
            if value and value not in CANONICAL_PRODUCT_CODES
        }
    )
    if remaining:
        print("[billing] Unrecognized entitlement product_code values:", ", ".join(remaining))


def _normalize_seat_allocations(apps, db_alias: str):
    SeatAllocation = apps.get_model("billing", "SeatAllocation")
    for legacy_code, canonical_product_code in PRODUCT_CODE_MAP.items():
        SeatAllocation.objects.using(db_alias).filter(product_code=legacy_code).update(
            product_code=canonical_product_code
        )

    remaining = sorted(
        {
            value
            for value in SeatAllocation.objects.using(db_alias)
            .values_list("product_code", flat=True)
            .distinct()
            if value and value not in CANONICAL_PRODUCT_CODES
        }
    )
    if remaining:
        print("[billing] Unrecognized seat allocation product_code values:", ", ".join(remaining))


def _normalize_seat_assignments(apps, db_alias: str):
    SeatAssignment = apps.get_model("billing", "SeatAssignment")
    queryset = SeatAssignment.objects.using(db_alias).filter(product_code__in=PRODUCT_CODE_MAP)
    for assignment in queryset.iterator(chunk_size=250):
        canonical_product_code = PRODUCT_CODE_MAP[assignment.product_code]
        if assignment.ended_at is None:
            duplicate = SeatAssignment.objects.using(db_alias).filter(
                account_id=assignment.account_id,
                user_id=assignment.user_id,
                product_code=canonical_product_code,
                ended_at__isnull=True,
            )
            duplicate = duplicate.exclude(pk=assignment.pk).first()
            if duplicate is not None:
                assignment.delete()
                continue
        assignment.product_code = canonical_product_code
        assignment.save(update_fields=["product_code"])

    remaining = sorted(
        {
            value
            for value in SeatAssignment.objects.using(db_alias)
            .values_list("product_code", flat=True)
            .distinct()
            if value and value not in CANONICAL_PRODUCT_CODES
        }
    )
    if remaining:
        print("[billing] Unrecognized seat assignment product_code values:", ", ".join(remaining))


def forwards(apps, schema_editor):
    db_alias = schema_editor.connection.alias
    _normalize_entitlements(apps, db_alias)
    _normalize_seat_allocations(apps, db_alias)
    _normalize_seat_assignments(apps, db_alias)


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ("billing", "0003_backfill_legacy_lab_memberships"),
    ]

    operations = [
        migrations.RunPython(forwards, migrations.RunPython.noop),
    ]
