# simcore/ai/prompts/scenarios/__init__.py
"""This module contains scenarios for the AI prompt engine.

Directed scenarios are defined in the `{app}/prompts/scenarios` directory.

Directed scenarios are used to generate prompts for the AI prompt engine with
more specific context and details, such as specific patient information, history,
etc. Directed scenarios can be used for seeding specific scenarios to users as
opposed to Undirected scenarios where the scenario is almost fully generated by
the AI model with minimal guidance (from Prompt Sections).
"""
pass