# Generated by Django 6.0 on 2025-12-31 00:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('simulation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ABCEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype')),
                ('simulation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='simulation.simulation')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
        ),
        migrations.CreateModel(
            name='Intervention',
            fields=[
                ('abcevent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='trainerlab.abcevent')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('trainerlab.abcevent',),
        ),
        migrations.CreateModel(
            name='VitalMeasurement',
            fields=[
                ('abcevent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='trainerlab.abcevent')),
                ('min_value', models.PositiveSmallIntegerField(help_text='Minimum value for range of this vital sign')),
                ('max_value', models.PositiveSmallIntegerField(help_text='Maximum value for range of this vital sign')),
                ('lock_value', models.BooleanField(default=False, help_text='Lock the value to the minimum (instead of a range between min and max)')),
            ],
            bases=('trainerlab.abcevent',),
        ),
        migrations.CreateModel(
            name='TrainerSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('simulation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_session', related_query_name='%(app_label)s_session', to='simulation.simulation')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Injury',
            fields=[
                ('abcevent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='trainerlab.abcevent')),
                ('injury_category', models.CharField(choices=[('M', 'Massive Hemorrhage'), ('A', 'Airway'), ('R', 'Respiration'), ('C', 'Circulatory'), ('H1', 'Hypothermia'), ('H2', 'Head Injury'), ('PC', 'Prolonged Field Care')], db_index=True, help_text='The category of the injury', max_length=2)),
                ('injury_location', models.CharField(choices=[('HLA', 'Left Anterior Head'), ('HRA', 'Right Anterior Head'), ('HLP', 'Left Posterior Head'), ('HRP', 'Right Posterior Head'), ('NLA', 'Left Anterior Neck'), ('NRA', 'Right Anterior Neck'), ('NLP', 'Left Posterior Neck'), ('NRP', 'Right Posterior Neck'), ('LUA', 'Left Upper Arm'), ('LLA', 'Left Lower Arm'), ('RUA', 'Right Upper Arm'), ('RLA', 'Right Lower Arm'), ('TLA', 'Left Anterior Chest'), ('TRA', 'Right Anterior Chest'), ('TLP', 'Left Posterior Chest'), ('TRP', 'Right Posterior Chest'), ('ALA', 'Left Anterior Abdomen'), ('ARA', 'Right Anterior Abdomen'), ('ALP', 'Left Posterior Abdomen'), ('ARP', 'Right Posterior Abdomen'), ('LUL', 'Left Upper Leg'), ('LLL', 'Left Lower Leg'), ('RUL', 'Right Upper Leg'), ('RLL', 'Right Lower Leg'), ('JLX', 'Left Junctional Axilla'), ('JRX', 'Right Junctional Axilla'), ('JLI', 'Left Junctional Inguinal'), ('JRI', 'Right Junctional Inguinal'), ('JLN', 'Left Junctional Neck'), ('JRN', 'Right Junctional Neck')], db_index=True, help_text='The location of the injury', max_length=4)),
                ('injury_kind', models.CharField(choices=[('AMP', 'Amputation'), ('PAMP', 'Partial Amputation'), ('LAC', 'Laceration'), ('LIC', 'Internal Laceration'), ('BURN', 'Burn'), ('PUN', 'Puncture'), ('PEN', 'Penetration'), ('GSW', 'Gunshot Wound'), ('SHR', 'Shrapnel')], db_index=True, help_text='The kind of injury', max_length=4)),
                ('injury_description', models.CharField(max_length=100)),
                ('is_treated', models.BooleanField(default=False)),
                ('is_resolved', models.BooleanField(default=False)),
                ('parent_injury', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children_injuries', to='trainerlab.injury')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('trainerlab.abcevent',),
        ),
        migrations.CreateModel(
            name='BloodGlucoseLevel',
            fields=[
                ('vitalmeasurement_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='trainerlab.vitalmeasurement')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('trainerlab.vitalmeasurement',),
        ),
        migrations.CreateModel(
            name='BloodPressure',
            fields=[
                ('vitalmeasurement_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='trainerlab.vitalmeasurement')),
                ('min_value_diastolic', models.PositiveSmallIntegerField()),
                ('max_value_diastolic', models.PositiveSmallIntegerField()),
            ],
            bases=('trainerlab.vitalmeasurement',),
        ),
        migrations.CreateModel(
            name='ETCO2',
            fields=[
                ('vitalmeasurement_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='trainerlab.vitalmeasurement')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('trainerlab.vitalmeasurement',),
        ),
        migrations.CreateModel(
            name='HeartRate',
            fields=[
                ('vitalmeasurement_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='trainerlab.vitalmeasurement')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('trainerlab.vitalmeasurement',),
        ),
        migrations.CreateModel(
            name='SPO2',
            fields=[
                ('vitalmeasurement_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='trainerlab.vitalmeasurement')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('trainerlab.vitalmeasurement',),
        ),
        migrations.AddConstraint(
            model_name='vitalmeasurement',
            constraint=models.CheckConstraint(condition=models.Q(('min_value__lte', models.F('max_value'))), name='vital_min_le_max'),
        ),
        migrations.AddConstraint(
            model_name='bloodpressure',
            constraint=models.CheckConstraint(condition=models.Q(('min_value_diastolic__lte', models.F('max_value_diastolic'))), name='bp_dia_min_le_max'),
        ),
    ]
