# Generated by Django 5.2 on 2025-05-18 13:07

import autoslug.fields
import django.db.models.deletion
import simcore.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Simulation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_timestamp', models.DateTimeField(auto_now_add=True)),
                ('end_timestamp', models.DateTimeField(blank=True, null=True)),
                ('time_limit', models.DurationField(blank=True, help_text='Optional max duration for this simulation', null=True)),
                ('openai_model', models.CharField(blank=True, max_length=128, null=True)),
                ('metadata_checksum', models.CharField(blank=True, max_length=64, null=True)),
                ('prompt', models.JSONField(help_text='The prompt to use as AI instructions')),
                ('diagnosis', models.CharField(blank=True, max_length=255, null=True)),
                ('chief_complaint', models.CharField(blank=True, max_length=255, null=True)),
                ('sim_patient_full_name', models.CharField(blank=True, max_length=100)),
                ('sim_patient_display_name', models.CharField(blank=True, max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SimulationImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('mime_type', models.CharField(blank=True, max_length=100, null=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, help_text='Unique identifier for this image', unique=True)),
                ('description', models.CharField(blank=True, help_text='3-5 words describing the image', max_length=100, null=True)),
                ('slug', autoslug.fields.AutoSlugField(always_update=True, editable=False, populate_from=simcore.models.slug_source, unique_with=('simulation',))),
                ('original', models.ImageField(height_field='original_height', upload_to=simcore.models.get_image_path, verbose_name='image', width_field='original_width')),
                ('original_height', models.PositiveIntegerField(blank=True, editable=False, null=True)),
                ('original_width', models.PositiveIntegerField(blank=True, editable=False, null=True)),
                ('simulation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='simcore.simulation')),
            ],
        ),
        migrations.CreateModel(
            name='SimulationMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(max_length=255)),
                ('attribute', models.CharField(max_length=64)),
                ('value', models.CharField(max_length=2000)),
                ('simulation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metadata', to='simcore.simulation')),
            ],
        ),
    ]
