# Generated by Django 5.2 on 2025-04-20 19:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('simai', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Simulation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_timestamp', models.DateTimeField(auto_now_add=True)),
                ('end_timestamp', models.DateTimeField(blank=True, null=True)),
                ('time_limit', models.DurationField(blank=True, help_text='Optional max duration for this simulation', null=True)),
                ('openai_model', models.CharField(blank=True, max_length=128, null=True)),
                ('metadata_checksum', models.CharField(blank=True, max_length=64, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('sim_patient_full_name', models.CharField(blank=True, max_length=100)),
                ('sim_patient_display_name', models.CharField(blank=True, max_length=100)),
                ('diagnosis', models.TextField(blank=True, max_length=100, null=True)),
                ('prompt', models.ForeignKey(help_text='The prompt to use as AI instructions.', on_delete=django.db.models.deletion.RESTRICT, to='simai.prompt')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SimulationMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(max_length=255)),
                ('attribute', models.CharField(max_length=64)),
                ('value', models.CharField(max_length=2000)),
                ('simulation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metadata', to='simcore.simulation')),
            ],
        ),
    ]
