# Generated by Django 5.2.1 on 2025-06-08 11:11

import autoslug.fields
import django.db.models.deletion
import simcore.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SimulationMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(max_length=255)),
                ('value', models.CharField(max_length=2000)),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
        ),
        migrations.CreateModel(
            name='Simulation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_timestamp', models.DateTimeField(auto_now_add=True)),
                ('end_timestamp', models.DateTimeField(blank=True, null=True)),
                ('time_limit', models.DurationField(blank=True, help_text='Optional max duration for this simulation', null=True)),
                ('openai_model', models.CharField(blank=True, max_length=128, null=True)),
                ('metadata_checksum', models.CharField(blank=True, max_length=64, null=True)),
                ('prompt', models.JSONField(help_text='The prompt to use as AI instructions')),
                ('diagnosis', models.CharField(blank=True, max_length=255, null=True)),
                ('chief_complaint', models.CharField(blank=True, max_length=255, null=True)),
                ('sim_patient_full_name', models.CharField(blank=True, max_length=100)),
                ('sim_patient_display_name', models.CharField(blank=True, max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LabResult',
            fields=[
                ('simulationmetadata_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='simcore.simulationmetadata')),
                ('result_unit', models.CharField(max_length=20)),
                ('reference_range_low', models.CharField(max_length=20)),
                ('reference_range_high', models.CharField(max_length=20)),
                ('result_flag', models.CharField(max_length=20)),
                ('result_comment', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('simcore.simulationmetadata',),
        ),
        migrations.CreateModel(
            name='PatientDemographics',
            fields=[
                ('simulationmetadata_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='simcore.simulationmetadata')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('simcore.simulationmetadata',),
        ),
        migrations.CreateModel(
            name='PatientHistory',
            fields=[
                ('simulationmetadata_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='simcore.simulationmetadata')),
                ('is_resolved', models.BooleanField(default=False)),
                ('duration', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('simcore.simulationmetadata',),
        ),
        migrations.CreateModel(
            name='RadResult',
            fields=[
                ('simulationmetadata_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='simcore.simulationmetadata')),
                ('result_flag', models.CharField(max_length=10)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('simcore.simulationmetadata',),
        ),
        migrations.CreateModel(
            name='SimulationFeedback',
            fields=[
                ('simulationmetadata_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='simcore.simulationmetadata')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('simcore.simulationmetadata',),
        ),
        migrations.AddField(
            model_name='simulationmetadata',
            name='simulation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metadata', to='simcore.simulation'),
        ),
        migrations.CreateModel(
            name='SimulationImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('mime_type', models.CharField(blank=True, max_length=100, null=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, help_text='Unique identifier for this image', unique=True)),
                ('description', models.CharField(blank=True, help_text='3-5 words describing the image', max_length=100, null=True)),
                ('slug', autoslug.fields.AutoSlugField(always_update=True, editable=False, populate_from=simcore.models.slug_source, unique_with=('simulation',))),
                ('original', models.ImageField(height_field='original_height', upload_to=simcore.models.get_image_path, verbose_name='image', width_field='original_width')),
                ('original_height', models.PositiveIntegerField(blank=True, editable=False, null=True)),
                ('original_width', models.PositiveIntegerField(blank=True, editable=False, null=True)),
                ('simulation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='simcore.simulation')),
            ],
        ),
    ]
