# Generated by Django 5.2 on 2025-04-06 23:27
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("content", models.TextField(blank=True, null=True)),
                (
                    "role",
                    models.CharField(
                        choices=[("U", "user"), ("A", "assistant")],
                        default="U",
                        max_length=2,
                    ),
                ),
                ("is_read", models.BooleanField(default=False)),
                (
                    "order",
                    models.PositiveIntegerField(blank=True, editable=False, null=True),
                ),
                ("openai_id", models.CharField(blank=True, max_length=255, null=True)),
                ("display_name", models.CharField(blank=True, max_length=100)),
            ],
            options={
                "ordering": ["timestamp"],
            },
        ),
        migrations.CreateModel(
            name="Prompt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("is_archived", models.BooleanField(default=False)),
                ("title", models.CharField(max_length=100)),
                (
                    "content",
                    models.TextField(help_text="The scenario prompt sent to OpenAI."),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Simulation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start", models.DateTimeField(auto_now_add=True)),
                ("end", models.DateTimeField(blank=True, null=True)),
                (
                    "time_limit",
                    models.DurationField(
                        blank=True,
                        help_text="Optional max duration for this simulation",
                        null=True,
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "metadata_checksum",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                ("sim_patient_full_name", models.CharField(blank=True, max_length=100)),
                (
                    "sim_patient_display_name",
                    models.CharField(blank=True, max_length=100),
                ),
                ("diagnosis", models.TextField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="SimulationMetafield",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("key", models.TextField()),
                ("value", models.TextField()),
            ],
        ),
    ]
