# Generated by Django 6.0.4 on 2026-04-26 12:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FeedbackAuditEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("created", "Created"),
                            ("marked_reviewed", "Marked Reviewed"),
                            ("status_changed", "Status Changed"),
                            ("archived", "Archived"),
                            ("unarchived", "Unarchived"),
                            ("remark_added", "Remark Added"),
                            ("bulk_updated", "Bulk Updated"),
                            ("notification_email_failed", "Notification Email Failed"),
                            ("notification_email_sent", "Notification Email Sent"),
                            (
                                "legacy_internal_note_migrated",
                                "Legacy Internal Note Migrated",
                            ),
                        ],
                        db_index=True,
                        max_length=64,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("metadata_json", models.JSONField(blank=True, default=dict)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="feedback_audit_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Feedback Audit Event",
                "verbose_name_plural": "Feedback Audit Events",
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="FeedbackRemark",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("body", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="feedback_remarks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Developer Team Remark",
                "verbose_name_plural": "Developer Team Remarks",
                "ordering": ["created_at", "id"],
            },
        ),
        migrations.CreateModel(
            name="UserFeedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("lab_type", models.CharField(blank=True, default="", max_length=32)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("bug_report", "Bug Report"),
                            ("ux_issue", "UX Issue"),
                            ("simulation_content", "Simulation Content"),
                            ("feature_request", "Feature Request"),
                            ("other", "Other"),
                        ],
                        db_index=True,
                        max_length=32,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("in_app", "In App"),
                            ("testflight", "TestFlight"),
                            ("admin", "Admin"),
                            ("api", "API"),
                            ("unknown", "Unknown"),
                        ],
                        db_index=True,
                        default="in_app",
                        max_length=32,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("action_required", "Action Required"),
                            ("no_action_required", "No Action Required"),
                            ("planned", "Planned"),
                            ("resolved", "Resolved"),
                            ("duplicate", "Duplicate"),
                            ("wont_fix", "Won't Fix"),
                        ],
                        db_index=True,
                        default="new",
                        max_length=32,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        default="",
                        max_length=32,
                    ),
                ),
                ("title", models.CharField(blank=True, default="", max_length=255)),
                ("body", models.TextField()),
                ("rating", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("email", models.EmailField(blank=True, default="", max_length=254)),
                ("allow_follow_up", models.BooleanField(default=True)),
                (
                    "client_platform",
                    models.CharField(
                        choices=[
                            ("ios", "iOS"),
                            ("web", "Web"),
                            ("android", "Android"),
                            ("unknown", "Unknown"),
                        ],
                        db_index=True,
                        default="unknown",
                        max_length=32,
                    ),
                ),
                (
                    "client_version",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "os_version",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "device_model",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "request_id",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "session_identifier",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("context_json", models.JSONField(blank=True, default=dict)),
                ("attachments_json", models.JSONField(blank=True, default=list)),
                ("is_reviewed", models.BooleanField(db_index=True, default=False)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("is_archived", models.BooleanField(db_index=True, default=False)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                (
                    "account",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="feedback_submissions",
                        to="accounts.account",
                    ),
                ),
                (
                    "archived_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="archived_feedback",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Feedback",
                "verbose_name_plural": "User Feedback",
                "ordering": ["-created_at"],
            },
        ),
    ]
