# Generated by Django 6.0.4 on 2026-04-26 23:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('feedback', '0001_initial'),
        ('simcore', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userfeedback',
            name='conversation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_feedback', to='simcore.conversation'),
        ),
        migrations.AddField(
            model_name='userfeedback',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_feedback', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userfeedback',
            name='simulation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_feedback', to='simcore.simulation'),
        ),
        migrations.AddField(
            model_name='userfeedback',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedback_submissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='feedbackremark',
            name='feedback',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remarks', to='feedback.userfeedback'),
        ),
        migrations.AddField(
            model_name='feedbackauditevent',
            name='feedback',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_events', to='feedback.userfeedback'),
        ),
        migrations.AddIndex(
            model_name='userfeedback',
            index=models.Index(fields=['is_archived', 'is_reviewed', '-created_at'], name='feedback_inbox_idx'),
        ),
        migrations.AddIndex(
            model_name='feedbackremark',
            index=models.Index(fields=['feedback', 'created_at'], name='feedback_remark_time_idx'),
        ),
        migrations.AddIndex(
            model_name='feedbackauditevent',
            index=models.Index(fields=['feedback', '-created_at'], name='feedback_audit_time_idx'),
        ),
        migrations.AddIndex(
            model_name='feedbackauditevent',
            index=models.Index(fields=['event_type', '-created_at'], name='feedback_audit_type_idx'),
        ),
    ]
