# Generated by Django 6.0.4 on 2026-04-21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils import timezone


def migrate_legacy_feedback_workflow(apps, schema_editor):
    UserFeedback = apps.get_model("feedback", "UserFeedback")
    FeedbackAuditEvent = apps.get_model("feedback", "FeedbackAuditEvent")
    now = timezone.now()
    status_map = {
        "new": "new",
        "triaged": "action_required",
        "planned": "planned",
        "resolved": "resolved",
        "duplicate": "duplicate",
        "wont_fix": "wont_fix",
    }
    reviewed_statuses = {
        "action_required",
        "no_action_required",
        "planned",
        "resolved",
        "duplicate",
        "wont_fix",
    }

    for feedback in UserFeedback.objects.all().iterator():
        old_status = feedback.status
        new_status = status_map.get(old_status, "new")
        is_reviewed = new_status in reviewed_statuses
        feedback.status = new_status
        feedback.is_reviewed = is_reviewed
        if is_reviewed:
            feedback.reviewed_at = feedback.resolved_at or now
            feedback.reviewed_by_id = feedback.resolved_by_id
        feedback.save(
            update_fields=[
                "status",
                "is_reviewed",
                "reviewed_at",
                "reviewed_by",
                "updated_at",
            ]
        )

        internal_notes = (feedback.internal_notes or "").strip()
        if internal_notes:
            FeedbackAuditEvent.objects.create(
                feedback_id=feedback.pk,
                actor_id=feedback.resolved_by_id,
                event_type="legacy_internal_note_migrated",
                metadata_json={
                    "body": internal_notes,
                    "old_status": old_status,
                    "new_status": new_status,
                },
            )


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_rename_membership_indexes"),
        ("feedback", "0001_initial"),
        ("simcore", "0008_backfill_simulation_accounts"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FeedbackAuditEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("created", "Created"),
                            ("marked_reviewed", "Marked Reviewed"),
                            ("status_changed", "Status Changed"),
                            ("archived", "Archived"),
                            ("unarchived", "Unarchived"),
                            ("remark_added", "Remark Added"),
                            ("bulk_updated", "Bulk Updated"),
                            ("notification_email_failed", "Notification Email Failed"),
                            ("notification_email_sent", "Notification Email Sent"),
                            (
                                "legacy_internal_note_migrated",
                                "Legacy Internal Note Migrated",
                            ),
                        ],
                        db_index=True,
                        max_length=64,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("metadata_json", models.JSONField(blank=True, default=dict)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="feedback_audit_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "feedback",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audit_events",
                        to="feedback.userfeedback",
                    ),
                ),
            ],
            options={
                "verbose_name": "Feedback Audit Event",
                "verbose_name_plural": "Feedback Audit Events",
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="FeedbackRemark",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("body", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="feedback_remarks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "feedback",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="remarks",
                        to="feedback.userfeedback",
                    ),
                ),
            ],
            options={
                "verbose_name": "Developer Team Remark",
                "verbose_name_plural": "Developer Team Remarks",
                "ordering": ["created_at", "id"],
            },
        ),
        migrations.AddField(
            model_name="userfeedback",
            name="archived_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userfeedback",
            name="archived_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="archived_feedback",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="userfeedback",
            name="is_archived",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name="userfeedback",
            name="is_reviewed",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name="userfeedback",
            name="reviewed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userfeedback",
            name="reviewed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reviewed_feedback",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="userfeedback",
            name="client_platform",
            field=models.CharField(
                choices=[
                    ("ios", "iOS"),
                    ("web", "Web"),
                    ("android", "Android"),
                    ("unknown", "Unknown"),
                ],
                db_index=True,
                default="unknown",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="userfeedback",
            name="status",
            field=models.CharField(
                choices=[
                    ("new", "New"),
                    ("action_required", "Action Required"),
                    ("no_action_required", "No Action Required"),
                    ("planned", "Planned"),
                    ("resolved", "Resolved"),
                    ("duplicate", "Duplicate"),
                    ("wont_fix", "Won't Fix"),
                ],
                db_index=True,
                default="new",
                max_length=32,
            ),
        ),
        migrations.RunPython(migrate_legacy_feedback_workflow, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="userfeedback",
            name="internal_notes",
        ),
        migrations.RemoveField(
            model_name="userfeedback",
            name="resolved_at",
        ),
        migrations.RemoveField(
            model_name="userfeedback",
            name="resolved_by",
        ),
        migrations.AddIndex(
            model_name="userfeedback",
            index=models.Index(
                fields=["is_archived", "is_reviewed", "-created_at"],
                name="feedback_inbox_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="feedbackauditevent",
            index=models.Index(
                fields=["feedback", "-created_at"],
                name="feedback_audit_time_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="feedbackauditevent",
            index=models.Index(
                fields=["event_type", "-created_at"],
                name="feedback_audit_type_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="feedbackremark",
            index=models.Index(
                fields=["feedback", "created_at"],
                name="feedback_remark_time_idx",
            ),
        ),
    ]
