# Generated by Django 6.0 on 2026-02-14 13:42

import autoslug.fields
import django.db.models.deletion
import simulation.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('orchestrai_django', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SimulationMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(max_length=255)),
                ('value', models.TextField()),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype')),
                ('service_call_attempt', models.ForeignKey(blank=True, help_text='Link to service call attempt that produced this metadata', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='simulation_metadata', to='orchestrai_django.servicecallattempt')),
            ],
        ),
        migrations.CreateModel(
            name='Simulation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_timestamp', models.DateTimeField(auto_now_add=True)),
                ('end_timestamp', models.DateTimeField(blank=True, null=True)),
                ('time_limit', models.DurationField(blank=True, help_text='Optional max duration for this simulation', null=True)),
                ('openai_model', models.CharField(blank=True, max_length=128, null=True)),
                ('metadata_checksum', models.CharField(blank=True, max_length=64, null=True)),
                ('prompt_instruction', models.TextField(default='', help_text='The prompt to use as AI instructions')),
                ('prompt_message', models.TextField(blank=True, help_text='The prompt to use as AI message', null=True)),
                ('prompt_meta', models.JSONField(blank=True, help_text='The prompt metadata to use as AI message', null=True)),
                ('diagnosis', models.CharField(blank=True, max_length=255, null=True)),
                ('chief_complaint', models.CharField(blank=True, max_length=255, null=True)),
                ('sim_patient_full_name', models.CharField(blank=True, max_length=100)),
                ('sim_patient_display_name', models.CharField(blank=True, max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LabResult',
            fields=[
                ('simulationmetadata_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='simulation.simulationmetadata')),
                ('panel_name', models.CharField(blank=True, max_length=100, null=True)),
                ('result_unit', models.CharField(blank=True, max_length=20, null=True)),
                ('reference_range_low', models.CharField(blank=True, max_length=50, null=True)),
                ('reference_range_high', models.CharField(blank=True, max_length=50, null=True)),
                ('result_flag', models.CharField(max_length=20)),
                ('result_comment', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('simulation.simulationmetadata',),
        ),
        migrations.CreateModel(
            name='PatientDemographics',
            fields=[
                ('simulationmetadata_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='simulation.simulationmetadata')),
            ],
            options={
                'abstract': False,
            },
            bases=('simulation.simulationmetadata',),
        ),
        migrations.CreateModel(
            name='PatientHistory',
            fields=[
                ('simulationmetadata_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='simulation.simulationmetadata')),
                ('is_resolved', models.BooleanField(default=False)),
                ('duration', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
            bases=('simulation.simulationmetadata',),
        ),
        migrations.CreateModel(
            name='RadResult',
            fields=[
                ('simulationmetadata_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='simulation.simulationmetadata')),
                ('result_flag', models.CharField(max_length=10)),
            ],
            options={
                'abstract': False,
            },
            bases=('simulation.simulationmetadata',),
        ),
        migrations.CreateModel(
            name='SimulationFeedback',
            fields=[
                ('simulationmetadata_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='simulation.simulationmetadata')),
            ],
            options={
                'abstract': False,
            },
            bases=('simulation.simulationmetadata',),
        ),
        migrations.AddField(
            model_name='simulationmetadata',
            name='simulation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metadata', to='simulation.simulation'),
        ),
        migrations.CreateModel(
            name='SimulationImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('mime_type', models.CharField(blank=True, max_length=100, null=True)),
                ('provider_id', models.CharField(blank=True, help_text='OpenAI image ID (if applicable)', max_length=255, null=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, help_text='Unique identifier for this image', unique=True)),
                ('description', models.CharField(blank=True, help_text='3-5 words describing the image', max_length=100, null=True)),
                ('slug', autoslug.fields.AutoSlugField(always_update=True, editable=False, populate_from=simulation.models.slug_source, unique_with=('simulation',))),
                ('original', models.ImageField(height_field='original_height', upload_to=simulation.models.get_image_path, verbose_name='image', width_field='original_width')),
                ('original_height', models.PositiveIntegerField(blank=True, editable=False, null=True)),
                ('original_width', models.PositiveIntegerField(blank=True, editable=False, null=True)),
                ('simulation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='simulation.simulation')),
            ],
        ),
        migrations.AddConstraint(
            model_name='simulationmetadata',
            constraint=models.UniqueConstraint(fields=('simulation', 'key'), name='uniq_simulation_key'),
        ),
    ]
