# Generated by Django 6.0 on 2026-01-16 22:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orchestrai_django', '0005_add_ai_audit_models'),
        ('simulation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulationmetadata',
            name='ai_response_audit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='simulation_metadata', to='orchestrai_django.airesponseaudit'),
        ),
    ]
