# Generated by Django 6.0.4 on 2026-04-26 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SessionPresence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lab_type', models.CharField(choices=[('trainerlab', 'TrainerLab'), ('chatlab', 'ChatLab')], max_length=16)),
                ('guard_state', models.CharField(choices=[('active', 'Active'), ('idle', 'Idle'), ('warning', 'Warning'), ('paused_inactivity', 'Paused (Inactivity)'), ('paused_manual', 'Paused (Manual)'), ('paused_runtime_cap', 'Paused (Runtime Cap)'), ('locked_usage', 'Locked (Usage)'), ('ended', 'Ended')], default='active', max_length=32)),
                ('pause_reason', models.CharField(choices=[('none', 'None'), ('inactivity', 'Inactivity'), ('runtime_cap', 'Runtime Cap'), ('usage_limit', 'Usage Limit'), ('wall_clock_expiry', 'Wall-Clock Expiry'), ('manual', 'Manual'), ('user_ended', 'User Ended'), ('admin_ended', 'Admin Ended'), ('session_expiry', 'Session Expiry')], default='none', max_length=32)),
                ('last_presence_at', models.DateTimeField(blank=True, null=True)),
                ('client_visibility', models.CharField(choices=[('foreground', 'Foreground'), ('background', 'Background'), ('unknown', 'Unknown')], default='unknown', max_length=16)),
                ('last_visibility_change_at', models.DateTimeField(blank=True, null=True)),
                ('paused_at', models.DateTimeField(blank=True, null=True)),
                ('runtime_locked_at', models.DateTimeField(blank=True, null=True)),
                ('warning_sent_at', models.DateTimeField(blank=True, null=True)),
                ('wall_clock_started_at', models.DateTimeField(blank=True, null=True)),
                ('wall_clock_expires_at', models.DateTimeField(blank=True, null=True)),
                ('engine_runnable', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='UsageRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope_type', models.CharField(choices=[('session', 'Session'), ('user', 'User'), ('account', 'Account')], max_length=16)),
                ('lab_type', models.CharField(choices=[('trainerlab', 'TrainerLab'), ('chatlab', 'ChatLab')], max_length=16)),
                ('product_code', models.CharField(blank=True, default='', max_length=64)),
                ('period_start', models.DateTimeField()),
                ('period_end', models.DateTimeField(blank=True, null=True)),
                ('input_tokens', models.PositiveBigIntegerField(default=0)),
                ('output_tokens', models.PositiveBigIntegerField(default=0)),
                ('reasoning_tokens', models.PositiveBigIntegerField(default=0)),
                ('total_tokens', models.PositiveBigIntegerField(default=0)),
                ('service_call_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
