# Generated by Django 6.0.4 on 2026-04-26 23:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('guards', '0001_initial'),
        ('simcore', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionpresence',
            name='simulation',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='guard_presence', to='simcore.simulation'),
        ),
        migrations.AddField(
            model_name='usagerecord',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usage_records', to='accounts.account'),
        ),
        migrations.AddField(
            model_name='usagerecord',
            name='simulation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usage_records', to='simcore.simulation'),
        ),
        migrations.AddField(
            model_name='usagerecord',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usage_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='sessionpresence',
            index=models.Index(fields=['guard_state', 'last_presence_at'], name='idx_guard_state_presence'),
        ),
        migrations.AddIndex(
            model_name='sessionpresence',
            index=models.Index(fields=['lab_type', 'guard_state'], name='idx_guard_lab_state'),
        ),
        migrations.AddIndex(
            model_name='sessionpresence',
            index=models.Index(fields=['engine_runnable'], name='idx_guard_engine_runnable'),
        ),
        migrations.AddIndex(
            model_name='usagerecord',
            index=models.Index(fields=['scope_type', 'simulation_id'], name='idx_usage_scope_sim'),
        ),
        migrations.AddIndex(
            model_name='usagerecord',
            index=models.Index(fields=['scope_type', 'user_id', 'period_start'], name='idx_usage_scope_user'),
        ),
        migrations.AddIndex(
            model_name='usagerecord',
            index=models.Index(fields=['scope_type', 'account_id', 'period_start'], name='idx_usage_scope_account'),
        ),
        migrations.AddIndex(
            model_name='usagerecord',
            index=models.Index(fields=['lab_type', 'product_code'], name='idx_usage_lab_product'),
        ),
        migrations.AddConstraint(
            model_name='usagerecord',
            constraint=models.UniqueConstraint(condition=models.Q(('scope_type', 'session')), fields=('scope_type', 'simulation_id', 'lab_type', 'product_code', 'period_start'), name='uniq_usage_session'),
        ),
        migrations.AddConstraint(
            model_name='usagerecord',
            constraint=models.UniqueConstraint(condition=models.Q(('scope_type', 'user')), fields=('scope_type', 'user_id', 'lab_type', 'product_code', 'period_start'), name='uniq_usage_user'),
        ),
        migrations.AddConstraint(
            model_name='usagerecord',
            constraint=models.UniqueConstraint(condition=models.Q(('scope_type', 'account')), fields=('scope_type', 'account_id', 'lab_type', 'product_code', 'period_start'), name='uniq_usage_account'),
        ),
    ]
