# Generated by Django 6.0 on 2025-12-30 23:09

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AIOutbox",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("orchestrai.request.sent", "AI request sent"),
                            ("orchestrai.response.received", "AI response received"),
                            ("orchestrai.response.ready", "AI response ready"),
                        ],
                        db_index=True,
                        max_length=64,
                    ),
                ),
                (
                    "correlation_id",
                    models.UUIDField(blank=True, db_index=True, null=True),
                ),
                (
                    "namespace",
                    models.CharField(
                        blank=True, db_index=True, max_length=255, null=True
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        blank=True, db_index=True, max_length=128, null=True
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, db_index=True, max_length=128, null=True
                    ),
                ),
                (
                    "provider_name",
                    models.CharField(
                        blank=True, db_index=True, max_length=64, null=True
                    ),
                ),
                (
                    "client_name",
                    models.CharField(
                        blank=True, db_index=True, max_length=128, null=True
                    ),
                ),
                ("payload", models.JSONField(default=dict)),
                (
                    "dispatched_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("attempts", models.PositiveIntegerField(default=0)),
                (
                    "next_attempt_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("last_error", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "ai_outbox",
                "indexes": [
                    models.Index(
                        fields=["event_type", "dispatched_at"],
                        name="ai_outbox_event_t_2f16ec_idx",
                    ),
                    models.Index(
                        fields=["namespace", "kind", "name"],
                        name="ai_outbox_namespa_7892b5_idx",
                    ),
                    models.Index(
                        fields=["namespace", "correlation_id"],
                        name="ai_outbox_namespa_7bbd72_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="AIRequestAudit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "correlation_id",
                    models.UUIDField(blank=True, db_index=True, null=True),
                ),
                (
                    "namespace",
                    models.CharField(
                        blank=True, db_index=True, max_length=255, null=True
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        blank=True, db_index=True, max_length=128, null=True
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, db_index=True, max_length=128, null=True
                    ),
                ),
                (
                    "provider_name",
                    models.CharField(
                        blank=True, db_index=True, max_length=64, null=True
                    ),
                ),
                (
                    "client_name",
                    models.CharField(
                        blank=True, db_index=True, max_length=128, null=True
                    ),
                ),
                (
                    "simulation_pk",
                    models.IntegerField(blank=True, db_index=True, null=True),
                ),
                ("model", models.CharField(blank=True, max_length=128, null=True)),
                ("stream", models.BooleanField(default=False)),
                ("messages", models.JSONField(default=list)),
                ("tools", models.JSONField(blank=True, null=True)),
                (
                    "response_format_cls",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("response_format_adapted", models.JSONField(blank=True, null=True)),
                ("response_format", models.JSONField(blank=True, null=True)),
                ("prompt_meta", models.JSONField(blank=True, null=True)),
            ],
            options={
                "db_table": "ai_request_audit",
                "indexes": [
                    models.Index(
                        fields=["provider_name", "client_name"],
                        name="ai_request__provide_26acab_idx",
                    ),
                    models.Index(
                        fields=["namespace", "name"],
                        name="ai_request__namespa_ccf62c_idx",
                    ),
                    models.Index(
                        fields=["correlation_id"], name="ai_request__correla_291a84_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ServiceCallRecord",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.CharField(max_length=64, primary_key=True, serialize=False),
                ),
                ("service_identity", models.CharField(db_index=True, max_length=255)),
                ("service_kwargs", models.JSONField(default=dict)),
                ("status", models.CharField(max_length=32)),
                ("input", models.JSONField(default=dict)),
                ("context", models.JSONField(blank=True, null=True)),
                ("result", models.JSONField(blank=True, null=True)),
                ("error", models.TextField(blank=True, null=True)),
                ("dispatch", models.JSONField(default=dict)),
                ("backend", models.CharField(default="immediate", max_length=64)),
                ("queue", models.CharField(blank=True, max_length=128, null=True)),
                ("task_id", models.CharField(blank=True, max_length=128, null=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "service_call_record",
                "indexes": [
                    models.Index(
                        fields=["service_identity", "backend"],
                        name="service_cal_service_570ca9_idx",
                    ),
                    models.Index(fields=["queue"], name="service_cal_queue_071896_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="AIResponseAudit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "correlation_id",
                    models.UUIDField(blank=True, db_index=True, null=True),
                ),
                (
                    "namespace",
                    models.CharField(
                        blank=True, db_index=True, max_length=255, null=True
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        blank=True, db_index=True, max_length=128, null=True
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, db_index=True, max_length=128, null=True
                    ),
                ),
                (
                    "provider_name",
                    models.CharField(
                        blank=True, db_index=True, max_length=64, null=True
                    ),
                ),
                (
                    "client_name",
                    models.CharField(
                        blank=True, db_index=True, max_length=128, null=True
                    ),
                ),
                (
                    "simulation_pk",
                    models.IntegerField(blank=True, db_index=True, null=True),
                ),
                (
                    "received_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("outputs", models.JSONField(default=list)),
                ("usage", models.JSONField(blank=True, null=True)),
                ("provider_meta", models.JSONField(blank=True, null=True)),
                ("error", models.TextField(blank=True, null=True)),
                (
                    "request",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="responses",
                        to="orchestrai_django.airequestaudit",
                    ),
                ),
            ],
            options={
                "db_table": "ai_response_audit",
                "indexes": [
                    models.Index(
                        fields=["provider_name", "client_name"],
                        name="ai_response_provide_ab2a35_idx",
                    ),
                    models.Index(
                        fields=["namespace", "name"],
                        name="ai_response_namespa_0e59d4_idx",
                    ),
                    models.Index(
                        fields=["correlation_id"], name="ai_response_correla_89cd0e_idx"
                    ),
                    models.Index(
                        fields=["received_at"], name="ai_response_receive_2cb20a_idx"
                    ),
                ],
            },
        ),
    ]
