# Generated by Django 6.0 on 2026-02-12 15:48

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceCall',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('service_identity', models.CharField(db_index=True, max_length=255)),
                ('service_kwargs', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=32)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('input', models.JSONField(default=dict)),
                ('context', models.JSONField(blank=True, null=True)),
                ('request', models.JSONField(blank=True, help_text='Full request JSON (debugging)', null=True)),
                ('output_data', models.JSONField(blank=True, help_text='result.output serialized - the validated schema data', null=True)),
                ('messages_json', models.JSONField(default=list, help_text='result.new_messages() for conversation continuation')),
                ('usage_json', models.JSONField(blank=True, help_text='Full RunUsage data', null=True)),
                ('model_name', models.CharField(blank=True, help_text='Model used for this call', max_length=128, null=True)),
                ('input_tokens', models.PositiveIntegerField(default=0)),
                ('output_tokens', models.PositiveIntegerField(default=0)),
                ('total_tokens', models.PositiveIntegerField(default=0)),
                ('error', models.TextField(blank=True, null=True)),
                ('domain_persisted', models.BooleanField(default=False)),
                ('domain_persist_error', models.TextField(blank=True, null=True)),
                ('domain_persist_attempts', models.IntegerField(default=0)),
                ('successful_attempt', models.PositiveIntegerField(blank=True, help_text='Attempt number that succeeded', null=True)),
                ('provider_response_id', models.CharField(blank=True, db_index=True, help_text='OpenAI response ID for conversation continuation', max_length=255, null=True)),
                ('previous_provider_response_id', models.CharField(blank=True, help_text='Previous response ID passed to provider', max_length=255, null=True)),
                ('correlation_id', models.UUIDField(db_index=True, default=uuid.uuid4, help_text='Correlation ID for tracing')),
                ('related_object_id', models.CharField(blank=True, db_index=True, help_text='ID of related domain object (e.g., simulation_id)', max_length=64, null=True)),
                ('schema_fqn', models.CharField(blank=True, db_index=True, help_text='Fully-qualified name of the Pydantic schema (e.g. chatlab.orca.schemas.patient.PatientInitialOutputSchema)', max_length=255, null=True)),
                ('backend', models.CharField(default='immediate', max_length=64)),
                ('queue', models.CharField(blank=True, max_length=128, null=True)),
                ('task_id', models.CharField(blank=True, max_length=128, null=True)),
                ('dispatch', models.JSONField(default=dict)),
            ],
            options={
                'db_table': 'service_call',
                'indexes': [models.Index(fields=['service_identity', 'status'], name='service_cal_service_e0f973_idx'), models.Index(fields=['status', 'domain_persisted', 'finished_at'], name='service_cal_status_b3ebb3_idx'), models.Index(fields=['related_object_id', '-finished_at'], name='service_cal_related_188951_idx'), models.Index(fields=['related_object_id', 'status', '-finished_at'], name='service_cal_related_f4daab_idx')],
            },
        ),
        migrations.CreateModel(
            name='ServiceCallAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attempt', models.PositiveIntegerField(help_text='1-indexed attempt number')),
                ('attempt_correlation_id', models.UUIDField(db_index=True, default=uuid.uuid4, help_text='Unique correlation ID for this attempt')),
                ('status', models.CharField(choices=[('built', 'Built'), ('dispatched', 'Dispatched'), ('received', 'Received'), ('schema_ok', 'Schema OK'), ('error', 'Error'), ('timeout', 'Timeout')], default='built', max_length=32)),
                ('request', models.JSONField(blank=True, help_text='Full request JSON (debugging)', null=True)),
                ('request_raw', models.JSONField(blank=True, help_text='Full Request JSON', null=True)),
                ('request_messages', models.JSONField(default=list, help_text='Extracted input messages for querying')),
                ('request_tools', models.JSONField(blank=True, help_text='Tools passed to provider', null=True)),
                ('schema_fqn', models.CharField(blank=True, help_text='Fully-qualified Python name of the response schema', max_length=255, null=True)),
                ('request_model', models.CharField(blank=True, help_text='Model requested for this attempt', max_length=128, null=True)),
                ('response_raw', models.JSONField(blank=True, help_text='Full OrchestrAI Response JSON', null=True)),
                ('response_provider_raw', models.JSONField(blank=True, help_text='Untouched provider response before normalization', null=True)),
                ('previous_provider_response_id', models.CharField(blank=True, help_text='Previous provider response ID attached to this request', max_length=255, null=True)),
                ('provider_response_id', models.CharField(blank=True, help_text="Provider's response ID (e.g., OpenAI response ID)", max_length=255, null=True)),
                ('structured_data', models.JSONField(blank=True, help_text='Validated structured output from response', null=True)),
                ('finish_reason', models.CharField(blank=True, help_text="Provider's finish reason", max_length=64, null=True)),
                ('input_tokens', models.PositiveIntegerField(default=0)),
                ('output_tokens', models.PositiveIntegerField(default=0)),
                ('total_tokens', models.PositiveIntegerField(default=0)),
                ('reasoning_tokens', models.PositiveIntegerField(default=0)),
                ('dispatched_at', models.DateTimeField(blank=True, help_text='When request was sent to provider', null=True)),
                ('received_at', models.DateTimeField(blank=True, help_text='When response was received from provider', null=True)),
                ('error', models.TextField(blank=True, help_text='Error message if attempt failed', null=True)),
                ('is_retryable', models.BooleanField(default=True, help_text='Whether this error should trigger a retry')),
                ('is_streaming', models.BooleanField(default=False, help_text='Whether this attempt used streaming')),
                ('service_call', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='orchestrai_django.servicecall')),
            ],
            options={
                'db_table': 'service_call_attempt',
                'indexes': [models.Index(fields=['service_call', 'attempt'], name='service_cal_service_c10486_idx'), models.Index(fields=['status'], name='service_cal_status_d648a9_idx'), models.Index(fields=['attempt_correlation_id'], name='service_cal_attempt_e86b48_idx'), models.Index(fields=['dispatched_at'], name='service_cal_dispatc_cf1fb0_idx')],
                'constraints': [models.UniqueConstraint(fields=('service_call', 'attempt'), name='unique_call_attempt')],
            },
        ),
    ]
