# Generated by Django 6.0 on 2026-01-24 21:10

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orchestrai_django', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceCall',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('service_identity', models.CharField(db_index=True, max_length=255)),
                ('service_kwargs', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=32)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('input', models.JSONField(default=dict)),
                ('context', models.JSONField(blank=True, null=True)),
                ('output_data', models.JSONField(blank=True, help_text='result.output serialized - the validated schema data', null=True)),
                ('messages_json', models.JSONField(default=list, help_text='result.new_messages() for conversation continuation')),
                ('usage_json', models.JSONField(blank=True, help_text='Full RunUsage data', null=True)),
                ('model_name', models.CharField(blank=True, help_text='Model used for this call', max_length=128, null=True)),
                ('input_tokens', models.PositiveIntegerField(default=0)),
                ('output_tokens', models.PositiveIntegerField(default=0)),
                ('total_tokens', models.PositiveIntegerField(default=0)),
                ('error', models.TextField(blank=True, null=True)),
                ('domain_persisted', models.BooleanField(default=False)),
                ('domain_persist_error', models.TextField(blank=True, null=True)),
                ('openai_response_id', models.CharField(blank=True, db_index=True, help_text='OpenAI response ID for conversation continuation', max_length=255, null=True)),
                ('correlation_id', models.UUIDField(db_index=True, default=uuid.uuid4, help_text='Correlation ID for tracing')),
                ('related_object_id', models.CharField(blank=True, db_index=True, help_text='ID of related domain object (e.g., simulation_id)', max_length=64, null=True)),
                ('backend', models.CharField(default='immediate', max_length=64)),
                ('task_id', models.CharField(blank=True, max_length=128, null=True)),
            ],
            options={
                'db_table': 'service_call',
                'indexes': [models.Index(fields=['service_identity', 'status'], name='service_cal_service_e0f973_idx'), models.Index(fields=['status', 'domain_persisted'], name='service_cal_status_d71225_idx'), models.Index(fields=['related_object_id', '-finished_at'], name='service_cal_related_188951_idx')],
            },
        ),
    ]
