# Generated by Django 6.0 on 2026-01-01 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orchestrai_django', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='airequestaudit',
            name='ai_request__provide_26acab_idx',
        ),
        migrations.RemoveIndex(
            model_name='airequestaudit',
            name='ai_request__namespa_ccf62c_idx',
        ),
        migrations.RemoveIndex(
            model_name='airequestaudit',
            name='ai_request__correla_291a84_idx',
        ),
        migrations.RemoveIndex(
            model_name='airesponseaudit',
            name='ai_response_provide_ab2a35_idx',
        ),
        migrations.RemoveIndex(
            model_name='airesponseaudit',
            name='ai_response_namespa_0e59d4_idx',
        ),
        migrations.RemoveIndex(
            model_name='airesponseaudit',
            name='ai_response_correla_89cd0e_idx',
        ),
        migrations.RemoveIndex(
            model_name='airesponseaudit',
            name='ai_response_receive_2cb20a_idx',
        ),
        migrations.RemoveField(
            model_name='airesponseaudit',
            name='request',
        ),
        migrations.DeleteModel(
            name='AIRequestAudit',
        ),
        migrations.DeleteModel(
            name='AIResponseAudit',
        ),
    ]
