# Generated by Django 6.0 on 2026-02-07 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orchestrai_django', '0002_add_service_call_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicecall',
            name='schema_fqn',
            field=models.CharField(blank=True, db_index=True, help_text='Fully-qualified name of the Pydantic schema (e.g. chatlab.orca.schemas.patient.PatientInitialOutputSchema)', max_length=255, null=True),
        ),
    ]
