# Generated by Django 6.0 on 2026-01-02 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orchestrai_django', '0002_remove_redundant_audits'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicecallrecord',
            name='domain_persisted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='servicecallrecord',
            name='domain_persist_error',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='servicecallrecord',
            name='domain_persist_attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name='servicecallrecord',
            index=models.Index(
                fields=['status', 'domain_persisted', 'finished_at'],
                name='service_cal_status_domain_idx'
            ),
        ),
    ]
