# Generated by Django 6.0 on 2026-02-07 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orchestrai_django', '0003_add_schema_fqn_to_servicecall'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='persistedchunk',
            unique_together=None,
        ),
        migrations.RemoveIndex(
            model_name='persistedchunk',
            name='persisted_c_call_id_def450_idx',
        ),
        migrations.RemoveIndex(
            model_name='persistedchunk',
            name='persisted_c_namespa_a0a879_idx',
        ),
        migrations.RemoveIndex(
            model_name='persistedchunk',
            name='persisted_c_persist_b50f9e_idx',
        ),
        migrations.DeleteModel(
            name='PersistedChunk',
        ),
    ]
