# Generated by Django 6.0 on 2026-01-02 16:29

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('orchestrai_django', '0003_add_domain_persistence_tracking'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersistedChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('call_id', models.CharField(db_index=True, max_length=64)),
                ('schema_identity', models.CharField(db_index=True, max_length=255)),
                ('namespace', models.CharField(db_index=True, max_length=255)),
                ('handler_identity', models.CharField(max_length=255)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('persisted_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'persisted_chunk',
            },
        ),
        migrations.RenameIndex(
            model_name='servicecallrecord',
            new_name='service_cal_status_ffabf3_idx',
            old_name='service_cal_status_domain_idx',
        ),
        migrations.AddField(
            model_name='persistedchunk',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddIndex(
            model_name='persistedchunk',
            index=models.Index(fields=['call_id', 'schema_identity'], name='persisted_c_call_id_def450_idx'),
        ),
        migrations.AddIndex(
            model_name='persistedchunk',
            index=models.Index(fields=['namespace', 'schema_identity'], name='persisted_c_namespa_a0a879_idx'),
        ),
        migrations.AddIndex(
            model_name='persistedchunk',
            index=models.Index(fields=['persisted_at'], name='persisted_c_persist_b50f9e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='persistedchunk',
            unique_together={('call_id', 'schema_identity')},
        ),
    ]
