# Generated by Django 6.0 on 2026-01-16 22:03

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orchestrai_django', '0004_add_persisted_chunk_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIRequestAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('correlation_id', models.UUIDField(db_index=True)),
                ('service_identity', models.CharField(db_index=True, max_length=255)),
                ('namespace', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('kind', models.CharField(blank=True, max_length=128, null=True)),
                ('name', models.CharField(blank=True, max_length=128, null=True)),
                ('provider_name', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('client_name', models.CharField(blank=True, max_length=128, null=True)),
                ('model', models.CharField(blank=True, max_length=128, null=True)),
                ('raw', models.JSONField(help_text="Request.model_dump(mode='json')")),
                ('messages', models.JSONField(default=list, help_text='Extracted input messages')),
                ('tools', models.JSONField(blank=True, null=True)),
                ('response_schema_identity', models.CharField(blank=True, max_length=255, null=True)),
                ('object_db_pk', models.IntegerField(blank=True, db_index=True, null=True)),
                ('dispatched_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('next_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ai_request_audit',
            },
        ),
        migrations.CreateModel(
            name='AIResponseAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('correlation_id', models.UUIDField(db_index=True)),
                ('request_correlation_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('raw', models.JSONField(help_text="Response.model_dump(mode='json')")),
                ('provider_raw', models.JSONField(blank=True, help_text="provider_meta['raw'] - untouched provider response", null=True)),
                ('provider_name', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('client_name', models.CharField(blank=True, max_length=128, null=True)),
                ('model', models.CharField(blank=True, max_length=128, null=True)),
                ('finish_reason', models.CharField(blank=True, max_length=64, null=True)),
                ('provider_response_id', models.CharField(blank=True, max_length=255, null=True)),
                ('input_tokens', models.PositiveIntegerField(default=0)),
                ('output_tokens', models.PositiveIntegerField(default=0)),
                ('total_tokens', models.PositiveIntegerField(default=0)),
                ('reasoning_tokens', models.PositiveIntegerField(default=0)),
                ('structured_data', models.JSONField(blank=True, null=True)),
                ('execution_metadata', models.JSONField(default=dict)),
                ('received_at', models.DateTimeField(db_index=True)),
            ],
            options={
                'db_table': 'ai_response_audit',
            },
        ),
        migrations.RemoveIndex(
            model_name='aioutbox',
            name='ai_outbox_event_t_2f16ec_idx',
        ),
        migrations.RemoveIndex(
            model_name='aioutbox',
            name='ai_outbox_namespa_7892b5_idx',
        ),
        migrations.RemoveIndex(
            model_name='aioutbox',
            name='ai_outbox_namespa_7bbd72_idx',
        ),
        migrations.DeleteModel(
            name='AIOutbox',
        ),
        migrations.AddField(
            model_name='airequestaudit',
            name='service_call',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_requests', to='orchestrai_django.servicecallrecord'),
        ),
        migrations.AddField(
            model_name='airesponseaudit',
            name='ai_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='orchestrai_django.airequestaudit'),
        ),
        migrations.AddField(
            model_name='airesponseaudit',
            name='service_call',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_responses', to='orchestrai_django.servicecallrecord'),
        ),
        migrations.AddIndex(
            model_name='airequestaudit',
            index=models.Index(fields=['correlation_id'], name='ai_request__correla_291a84_idx'),
        ),
        migrations.AddIndex(
            model_name='airequestaudit',
            index=models.Index(fields=['service_identity'], name='ai_request__service_7f1962_idx'),
        ),
        migrations.AddIndex(
            model_name='airequestaudit',
            index=models.Index(fields=['namespace', 'kind', 'name'], name='ai_request__namespa_24c91d_idx'),
        ),
        migrations.AddIndex(
            model_name='airequestaudit',
            index=models.Index(fields=['provider_name', 'model'], name='ai_request__provide_686ea5_idx'),
        ),
        migrations.AddIndex(
            model_name='airequestaudit',
            index=models.Index(fields=['dispatched_at'], name='ai_request__dispatc_113bf5_idx'),
        ),
        migrations.AddIndex(
            model_name='airesponseaudit',
            index=models.Index(fields=['correlation_id'], name='ai_response_correla_89cd0e_idx'),
        ),
        migrations.AddIndex(
            model_name='airesponseaudit',
            index=models.Index(fields=['request_correlation_id'], name='ai_response_request_2d09fe_idx'),
        ),
        migrations.AddIndex(
            model_name='airesponseaudit',
            index=models.Index(fields=['provider_name', 'model'], name='ai_response_provide_d8d0bc_idx'),
        ),
        migrations.AddIndex(
            model_name='airesponseaudit',
            index=models.Index(fields=['received_at'], name='ai_response_receive_2cb20a_idx'),
        ),
    ]
