# Generated by Django 6.0.4 on 2026-04-26 23:25

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('orchestrai_django', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentCriterion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=80)),
                ('label', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('category', models.CharField(blank=True, default='', max_length=60)),
                ('value_type', models.CharField(choices=[('bool', 'Boolean'), ('int', 'Integer'), ('decimal', 'Decimal'), ('text', 'Text'), ('enum', 'Enum'), ('json', 'JSON')], max_length=10)),
                ('min_value', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('max_value', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('allowed_values', models.JSONField(blank=True, default=list)),
                ('weight', models.DecimalField(decimal_places=3, default=Decimal('1.000'), max_digits=6)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('required', models.BooleanField(default=True)),
                ('include_in_user_summary', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['rubric_id', 'sort_order'],
            },
        ),
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('assessment_type', models.CharField(db_index=True, max_length=60)),
                ('lab_type', models.CharField(blank=True, db_index=True, max_length=40)),
                ('period_start', models.DateTimeField(blank=True, null=True)),
                ('period_end', models.DateTimeField(blank=True, null=True)),
                ('overall_summary', models.TextField(blank=True, default='')),
                ('overall_score', models.DecimalField(blank=True, decimal_places=3, max_digits=4, null=True)),
                ('generated_by_service', models.CharField(blank=True, default='', max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='accounts.account')),
                ('assessed_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments_received', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assessments_authored', to=settings.AUTH_USER_MODEL)),
                ('source_attempt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assessments', to='orchestrai_django.servicecallattempt')),
            ],
        ),
        migrations.CreateModel(
            name='AssessmentCriterionScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_bool', models.BooleanField(blank=True, null=True)),
                ('value_int', models.IntegerField(blank=True, null=True)),
                ('value_decimal', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('value_text', models.TextField(blank=True, default='')),
                ('value_json', models.JSONField(blank=True, null=True)),
                ('score', models.DecimalField(blank=True, decimal_places=3, max_digits=4, null=True)),
                ('rationale', models.TextField(blank=True, default='')),
                ('evidence', models.JSONField(blank=True, default=list, help_text='Structured evidence list. Expected entries: {"type": "message", "message_id": int, "quote": str, "reason": str}.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criterion_scores', to='assessments.assessment')),
                ('criterion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scores', to='assessments.assessmentcriterion')),
            ],
        ),
        migrations.CreateModel(
            name='AssessmentRubric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=120)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('scope', models.CharField(choices=[('global', 'Global'), ('account', 'Account')], default='global', max_length=10)),
                ('lab_type', models.CharField(blank=True, db_index=True, max_length=40)),
                ('assessment_type', models.CharField(db_index=True, max_length=60)),
                ('version', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=10)),
                ('seed_source_app', models.CharField(blank=True, default='', max_length=80)),
                ('seed_source_path', models.CharField(blank=True, default='', max_length=255)),
                ('seed_checksum', models.CharField(blank=True, default='', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assessment_rubrics', to='accounts.account')),
                ('based_on', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='derivatives', to='assessments.assessmentrubric')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rubrics_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rubrics_updated', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='assessmentcriterion',
            name='rubric',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criteria', to='assessments.assessmentrubric'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='rubric',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assessments', to='assessments.assessmentrubric'),
        ),
        migrations.CreateModel(
            name='AssessmentSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('simulation', 'Simulation'), ('assessment', 'Assessment')], max_length=20)),
                ('role', models.CharField(choices=[('primary', 'Primary'), ('contributing', 'Contributing'), ('generated_from', 'Generated From'), ('evidence', 'Evidence')], default='primary', max_length=20)),
                ('notes', models.TextField(blank=True, default='')),
                ('snapshot', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='assessments.assessment')),
            ],
        ),
    ]
