"""Initial migration for the assessments app.

Hand-written rather than auto-generated. After Phase 5 (`reset_migrations
-m`) this file will be regenerated by `makemigrations` from a clean slate;
the regenerated form supersedes this one.
"""

import uuid
from decimal import Decimal

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("accounts", "0007_invitation_staging_reminder"),
        ("orchestrai_django", "0001_initial"),
        ("simcore", "0009_simulation_archival"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AssessmentRubric",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("slug", models.SlugField(max_length=120)),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "scope",
                    models.CharField(
                        choices=[("global", "Global"), ("account", "Account")],
                        default="global",
                        max_length=10,
                    ),
                ),
                ("lab_type", models.CharField(blank=True, db_index=True, max_length=40)),
                ("assessment_type", models.CharField(db_index=True, max_length=60)),
                ("version", models.PositiveIntegerField(default=1)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("published", "Published"),
                            ("archived", "Archived"),
                        ],
                        default="draft",
                        max_length=10,
                    ),
                ),
                ("seed_source_app", models.CharField(blank=True, default="", max_length=80)),
                ("seed_source_path", models.CharField(blank=True, default="", max_length=255)),
                ("seed_checksum", models.CharField(blank=True, default="", max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                (
                    "account",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assessment_rubrics",
                        to="accounts.account",
                    ),
                ),
                (
                    "based_on",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="derivatives",
                        to="assessments.assessmentrubric",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="rubrics_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="rubrics_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="assessmentrubric",
            index=models.Index(
                fields=["lab_type", "assessment_type", "status"],
                name="rubric_lab_type_status_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="assessmentrubric",
            index=models.Index(
                fields=["account", "status"], name="rubric_account_status_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="assessmentrubric",
            constraint=models.UniqueConstraint(
                condition=models.Q(("account__isnull", True)),
                fields=("slug", "version"),
                name="uniq_rubric_global_slug_version",
            ),
        ),
        migrations.AddConstraint(
            model_name="assessmentrubric",
            constraint=models.UniqueConstraint(
                condition=models.Q(("account__isnull", False)),
                fields=("account", "slug", "version"),
                name="uniq_rubric_account_slug_version",
            ),
        ),
        migrations.AddConstraint(
            model_name="assessmentrubric",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("scope", "account"), ("account__isnull", False)),
                    models.Q(("scope", "global"), ("account__isnull", True)),
                    _connector="OR",
                ),
                name="rubric_account_matches_scope",
            ),
        ),
        migrations.CreateModel(
            name="AssessmentCriterion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("slug", models.SlugField(max_length=80)),
                ("label", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, default="")),
                ("category", models.CharField(blank=True, default="", max_length=60)),
                (
                    "value_type",
                    models.CharField(
                        choices=[
                            ("bool", "Boolean"),
                            ("int", "Integer"),
                            ("decimal", "Decimal"),
                            ("text", "Text"),
                            ("enum", "Enum"),
                            ("json", "JSON"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "min_value",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=12, null=True
                    ),
                ),
                (
                    "max_value",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=12, null=True
                    ),
                ),
                ("allowed_values", models.JSONField(blank=True, default=list)),
                (
                    "weight",
                    models.DecimalField(
                        decimal_places=3, default=Decimal("1.000"), max_digits=6
                    ),
                ),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("required", models.BooleanField(default=True)),
                ("include_in_user_summary", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "rubric",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="criteria",
                        to="assessments.assessmentrubric",
                    ),
                ),
            ],
            options={"ordering": ["rubric_id", "sort_order"]},
        ),
        migrations.AddConstraint(
            model_name="assessmentcriterion",
            constraint=models.UniqueConstraint(
                fields=("rubric", "slug"), name="uniq_criterion_rubric_slug"
            ),
        ),
        migrations.AddConstraint(
            model_name="assessmentcriterion",
            constraint=models.CheckConstraint(
                condition=models.Q(("weight__gte", 0)),
                name="criterion_weight_nonnegative",
            ),
        ),
        migrations.CreateModel(
            name="Assessment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("assessment_type", models.CharField(db_index=True, max_length=60)),
                ("lab_type", models.CharField(blank=True, db_index=True, max_length=40)),
                ("period_start", models.DateTimeField(blank=True, null=True)),
                ("period_end", models.DateTimeField(blank=True, null=True)),
                ("overall_summary", models.TextField(blank=True, default="")),
                (
                    "overall_score",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=4, null=True
                    ),
                ),
                (
                    "generated_by_service",
                    models.CharField(blank=True, default="", max_length=120),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assessments",
                        to="accounts.account",
                    ),
                ),
                (
                    "assessed_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assessments_received",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assessments_authored",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "rubric",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="assessments",
                        to="assessments.assessmentrubric",
                    ),
                ),
                (
                    "source_attempt",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assessments",
                        to="orchestrai_django.servicecallattempt",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="assessment",
            index=models.Index(
                fields=["account", "lab_type", "assessment_type"],
                name="assessment_acct_lab_type_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="assessment",
            index=models.Index(
                fields=["assessed_user", "lab_type"], name="assessment_user_lab_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="assessment",
            index=models.Index(fields=["rubric"], name="assessment_rubric_idx"),
        ),
        migrations.AddConstraint(
            model_name="assessment",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("overall_score__isnull", True),
                    models.Q(
                        ("overall_score__gte", 0), ("overall_score__lte", 1)
                    ),
                    _connector="OR",
                ),
                name="assessment_overall_score_in_unit",
            ),
        ),
        migrations.CreateModel(
            name="AssessmentCriterionScore",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("value_bool", models.BooleanField(blank=True, null=True)),
                ("value_int", models.IntegerField(blank=True, null=True)),
                (
                    "value_decimal",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=12, null=True
                    ),
                ),
                ("value_text", models.TextField(blank=True, default="")),
                ("value_json", models.JSONField(blank=True, null=True)),
                (
                    "score",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=4, null=True
                    ),
                ),
                ("rationale", models.TextField(blank=True, default="")),
                (
                    "evidence",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text=(
                            'Structured evidence list. Expected entries: '
                            '{"type": "message", "message_id": int, '
                            '"quote": str, "reason": str}.'
                        ),
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assessment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="criterion_scores",
                        to="assessments.assessment",
                    ),
                ),
                (
                    "criterion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="scores",
                        to="assessments.assessmentcriterion",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="assessmentcriterionscore",
            constraint=models.UniqueConstraint(
                fields=("assessment", "criterion"),
                name="uniq_score_assessment_criterion",
            ),
        ),
        migrations.AddConstraint(
            model_name="assessmentcriterionscore",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("score__isnull", True),
                    models.Q(("score__gte", 0), ("score__lte", 1)),
                    _connector="OR",
                ),
                name="score_in_unit",
            ),
        ),
        migrations.CreateModel(
            name="AssessmentSource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("simulation", "Simulation"),
                            ("assessment", "Assessment"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("primary", "Primary"),
                            ("contributing", "Contributing"),
                            ("generated_from", "Generated From"),
                            ("evidence", "Evidence"),
                        ],
                        default="primary",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True, default="")),
                ("snapshot", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "assessment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sources",
                        to="assessments.assessment",
                    ),
                ),
                (
                    "simulation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assessment_sources",
                        to="simcore.simulation",
                    ),
                ),
                (
                    "source_assessment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="referenced_by_sources",
                        to="assessments.assessment",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="assessmentsource",
            index=models.Index(
                fields=["assessment", "role"], name="src_assessment_role_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="assessmentsource",
            index=models.Index(fields=["simulation"], name="src_simulation_idx"),
        ),
        migrations.AddIndex(
            model_name="assessmentsource",
            index=models.Index(
                fields=["source_assessment"], name="src_source_assessment_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="assessmentsource",
            constraint=models.UniqueConstraint(
                condition=models.Q(("role", "primary")),
                fields=("assessment", "role"),
                name="uniq_primary_source_per_assessment",
            ),
        ),
    ]
