# Generated by Django 6.0.4 on 2026-04-26 12:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("assessments", "0001_initial"),
        ("simcore", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="assessmentsource",
            name="simulation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="assessment_sources",
                to="simcore.simulation",
            ),
        ),
        migrations.AddField(
            model_name="assessmentsource",
            name="source_assessment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="referenced_by_sources",
                to="assessments.assessment",
            ),
        ),
        migrations.AddConstraint(
            model_name="assessmentcriterionscore",
            constraint=models.UniqueConstraint(
                fields=("assessment", "criterion"),
                name="uniq_score_assessment_criterion",
            ),
        ),
        migrations.AddConstraint(
            model_name="assessmentcriterionscore",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("score__isnull", True),
                    models.Q(("score__gte", 0), ("score__lte", 1)),
                    _connector="OR",
                ),
                name="score_in_unit",
            ),
        ),
        migrations.AddIndex(
            model_name="assessmentrubric",
            index=models.Index(
                fields=["lab_type", "assessment_type", "status"],
                name="rubric_lab_type_status_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="assessmentrubric",
            index=models.Index(
                fields=["account", "status"], name="rubric_account_status_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="assessmentrubric",
            constraint=models.UniqueConstraint(
                condition=models.Q(("account__isnull", True)),
                fields=("slug", "version"),
                name="uniq_rubric_global_slug_version",
            ),
        ),
        migrations.AddConstraint(
            model_name="assessmentrubric",
            constraint=models.UniqueConstraint(
                condition=models.Q(("account__isnull", False)),
                fields=("account", "slug", "version"),
                name="uniq_rubric_account_slug_version",
            ),
        ),
        migrations.AddConstraint(
            model_name="assessmentrubric",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("scope", "account"), ("account__isnull", False)),
                    models.Q(("scope", "global"), ("account__isnull", True)),
                    _connector="OR",
                ),
                name="rubric_account_matches_scope",
            ),
        ),
        migrations.AddConstraint(
            model_name="assessmentcriterion",
            constraint=models.UniqueConstraint(
                fields=("rubric", "slug"), name="uniq_criterion_rubric_slug"
            ),
        ),
        migrations.AddConstraint(
            model_name="assessmentcriterion",
            constraint=models.CheckConstraint(
                condition=models.Q(("weight__gte", 0)),
                name="criterion_weight_nonnegative",
            ),
        ),
        migrations.AddIndex(
            model_name="assessment",
            index=models.Index(
                fields=["account", "lab_type", "assessment_type"],
                name="assessment_acct_lab_type_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="assessment",
            index=models.Index(
                fields=["assessed_user", "lab_type"], name="assessment_user_lab_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="assessment",
            index=models.Index(fields=["rubric"], name="assessment_rubric_idx"),
        ),
        migrations.AddConstraint(
            model_name="assessment",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("overall_score__isnull", True),
                    models.Q(("overall_score__gte", 0), ("overall_score__lte", 1)),
                    _connector="OR",
                ),
                name="assessment_overall_score_in_unit",
            ),
        ),
        migrations.AddIndex(
            model_name="assessmentsource",
            index=models.Index(
                fields=["assessment", "role"], name="src_assessment_role_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="assessmentsource",
            index=models.Index(fields=["simulation"], name="src_simulation_idx"),
        ),
        migrations.AddIndex(
            model_name="assessmentsource",
            index=models.Index(
                fields=["source_assessment"], name="src_source_assessment_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="assessmentsource",
            constraint=models.UniqueConstraint(
                condition=models.Q(("role", "primary")),
                fields=("assessment", "role"),
                name="uniq_primary_source_per_assessment",
            ),
        ),
    ]
