# Generated by Django 6.0.3 on 2026-03-06 23:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def seed_trainerlab(apps, schema_editor):
    Lab = apps.get_model("accounts", "Lab")
    Lab.objects.get_or_create(
        slug="trainerlab",
        defaults={
            "display_name": "TrainerLab",
            "is_active": True,
        },
    )


def reverse_seed_trainerlab(apps, schema_editor):
    Lab = apps.get_model("accounts", "Lab")
    Lab.objects.filter(slug="trainerlab").delete()


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('display_name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('slug',),
            },
        ),
        migrations.CreateModel(
            name='LabMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_level', models.CharField(choices=[('viewer', 'Viewer'), ('instructor', 'Instructor'), ('admin', 'Admin')], default='instructor', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('granted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_lab_memberships', to=settings.AUTH_USER_MODEL)),
                ('lab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='accounts.lab')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['lab', 'is_active', 'access_level'], name='idx_lab_membership_acl'), models.Index(fields=['user', 'is_active'], name='idx_lab_membership_user')],
                'constraints': [models.UniqueConstraint(fields=('user', 'lab'), name='uniq_lab_membership_user_lab')],
            },
        ),
        migrations.RunPython(seed_trainerlab, reverse_seed_trainerlab),
    ]
