# Generated by Django 6.0.3 on 2026-03-23 12:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_lab_labmembership'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('account_type', models.CharField(choices=[('personal', 'Personal'), ('organization', 'Organization')], default='personal', max_length=32)),
                ('is_active', models.BooleanField(default=True)),
                ('requires_join_approval', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_accounts', to=settings.AUTH_USER_MODEL)),
                ('parent_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_accounts', to='accounts.account')),
            ],
            options={
                'ordering': ('name', 'id'),
            },
        ),
        migrations.AddField(
            model_name='user',
            name='active_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_for_users', to='accounts.account'),
        ),
        migrations.CreateModel(
            name='AccountAuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=100)),
                ('target_type', models.CharField(blank=True, default='', max_length=100)),
                ('target_ref', models.CharField(blank=True, default='', max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_events', to='accounts.account')),
                ('actor_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='account_audit_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='AccountMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('invite_email', models.EmailField(blank=True, default='', max_length=254)),
                ('role', models.CharField(choices=[('billing_admin', 'Billing Admin'), ('org_admin', 'Org Admin'), ('instructor', 'Instructor'), ('general_user', 'General User')], default='general_user', max_length=32)),
                ('status', models.CharField(choices=[('active', 'Active'), ('pending', 'Pending'), ('suspended', 'Suspended'), ('removed', 'Removed')], default='pending', max_length=32)),
                ('joined_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='accounts.account')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_account_memberships', to=settings.AUTH_USER_MODEL)),
                ('invited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invited_account_memberships', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='account_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('account_id', 'invite_email', 'id'),
            },
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['account_type', 'is_active'], name='idx_account_type_active'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['owner_user'], name='idx_account_owner_user'),
        ),
        migrations.AddConstraint(
            model_name='account',
            constraint=models.UniqueConstraint(condition=models.Q(('account_type', 'personal'), ('owner_user__isnull', False)), fields=('owner_user',), name='uniq_personal_account_owner_user'),
        ),
        migrations.AddIndex(
            model_name='accountauditevent',
            index=models.Index(fields=['account', 'created_at'], name='idx_account_audit_account'),
        ),
        migrations.AddIndex(
            model_name='accountauditevent',
            index=models.Index(fields=['event_type', 'created_at'], name='idx_account_audit_type'),
        ),
        migrations.AddIndex(
            model_name='accountmembership',
            index=models.Index(fields=['account', 'status', 'role'], name='idx_account_membership_acl'),
        ),
        migrations.AddIndex(
            model_name='accountmembership',
            index=models.Index(fields=['user', 'status'], name='idx_account_membership_user_status'),
        ),
        migrations.AddIndex(
            model_name='accountmembership',
            index=models.Index(fields=['invite_email', 'status'], name='idx_account_membership_invite_email'),
        ),
        migrations.AddConstraint(
            model_name='accountmembership',
            constraint=models.UniqueConstraint(condition=models.Q(('ended_at__isnull', True), ('user__isnull', False)), fields=('account', 'user'), name='uniq_open_account_membership_user'),
        ),
        migrations.AddConstraint(
            model_name='accountmembership',
            constraint=models.UniqueConstraint(condition=models.Q(('ended_at__isnull', True), ('invite_email__gt', '')), fields=('account', 'invite_email'), name='uniq_open_account_membership_email'),
        ),
    ]
