# Generated by Codex on 2026-03-23

from django.db import migrations
from django.utils import timezone


def _personal_account_name(user) -> str:
    full_name = " ".join(
        part.strip() for part in [getattr(user, "first_name", ""), getattr(user, "last_name", "")] if part
    ).strip()
    if full_name:
        return f"{full_name} Personal"
    email = (getattr(user, "email", "") or "").strip()
    if email:
        return f"{email.split('@', 1)[0]} Personal"
    return f"User {user.pk} Personal"


def forwards(apps, schema_editor):
    User = apps.get_model("accounts", "User")
    Account = apps.get_model("accounts", "Account")
    AccountMembership = apps.get_model("accounts", "AccountMembership")
    db_alias = schema_editor.connection.alias
    now = timezone.now()

    for user in User.objects.using(db_alias).all().iterator(chunk_size=250):
        account, _created = Account.objects.using(db_alias).get_or_create(
            owner_user_id=user.pk,
            account_type="personal",
            defaults={
                "name": _personal_account_name(user),
                "slug": f"personal-{user.pk}",
                "is_active": True,
                "requires_join_approval": False,
            },
        )
        AccountMembership.objects.using(db_alias).update_or_create(
            account_id=account.id,
            user_id=user.pk,
            ended_at__isnull=True,
            defaults={
                "invite_email": (getattr(user, "email", "") or "").strip().lower(),
                "role": "org_admin",
                "status": "active",
                "approved_by_id": user.pk,
                "joined_at": getattr(user, "date_joined", None) or now,
            },
        )
        if getattr(user, "active_account_id", None) is None:
            User.objects.using(db_alias).filter(pk=user.pk, active_account__isnull=True).update(
                active_account_id=account.id
            )


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ("accounts", "0003_account_user_active_account_accountauditevent_and_more"),
    ]

    operations = [
        migrations.RunPython(forwards, migrations.RunPython.noop),
    ]
