# Generated by Django 5.2 on 2025-04-20 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('role', models.CharField(choices=[('U', 'user'), ('A', 'assistant')], default='U', max_length=2)),
                ('is_read', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(blank=True, editable=False, null=True)),
                ('openai_id', models.CharField(blank=True, max_length=255, null=True)),
                ('display_name', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Simulation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_timestamp', models.DateTimeField(auto_now_add=True)),
                ('end_timestamp', models.DateTimeField(blank=True, null=True)),
                ('time_limit', models.DurationField(blank=True, help_text='Optional max duration for this simulation', null=True)),
                ('openai_model', models.CharField(blank=True, max_length=128, null=True)),
                ('metadata_checksum', models.CharField(blank=True, max_length=64, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('sim_patient_full_name', models.CharField(blank=True, max_length=100)),
                ('sim_patient_display_name', models.CharField(blank=True, max_length=100)),
                ('diagnosis', models.TextField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SimulationMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(max_length=255)),
                ('attribute', models.CharField(max_length=64)),
                ('value', models.CharField(max_length=2000)),
            ],
        ),
    ]
