# Generated by Django 5.2 on 2025-04-12 23:16
import ChatLab.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Prompt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("is_archived", models.BooleanField(default=False)),
                ("title", models.CharField(max_length=100)),
                (
                    "content",
                    models.TextField(help_text="The scenario prompt sent to OpenAI."),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_prompts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="modified_prompts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Simulation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start", models.DateTimeField(auto_now_add=True)),
                ("end", models.DateTimeField(blank=True, null=True)),
                (
                    "time_limit",
                    models.DurationField(
                        blank=True,
                        help_text="Optional max duration for this simulation",
                        null=True,
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "openai_model",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                (
                    "metadata_checksum",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                ("sim_patient_full_name", models.CharField(blank=True, max_length=100)),
                (
                    "sim_patient_display_name",
                    models.CharField(blank=True, max_length=100),
                ),
                ("diagnosis", models.TextField(blank=True, max_length=100, null=True)),
                (
                    "prompt",
                    models.ForeignKey(
                        blank=True,
                        default=ChatLab.models.get_default_prompt,
                        help_text="The prompt to use as AI instructions.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="ChatLab.prompt",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SimulationMetadata",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("key", models.CharField(max_length=64)),
                ("attribute", models.CharField(max_length=64)),
                ("value", models.CharField(max_length=255)),
                (
                    "simulation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="metadata",
                        to="ChatLab.simulation",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("content", models.TextField(blank=True, null=True)),
                (
                    "role",
                    models.CharField(
                        choices=[("U", "user"), ("A", "assistant")],
                        default="U",
                        max_length=2,
                    ),
                ),
                ("is_read", models.BooleanField(default=False)),
                (
                    "order",
                    models.PositiveIntegerField(blank=True, editable=False, null=True),
                ),
                ("openai_id", models.CharField(blank=True, max_length=255, null=True)),
                ("display_name", models.CharField(blank=True, max_length=100)),
                (
                    "sender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "simulation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ChatLab.simulation",
                    ),
                ),
            ],
            options={
                "ordering": ["timestamp"],
                "unique_together": {("simulation", "order")},
            },
        ),
    ]
