# Generated by Django 5.2.1 on 2025-06-28 14:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chatlab', '0001_initial'),
        ('simai', '0001_initial'),
        ('simcore', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='simulation',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='session', to='simcore.simulation'),
        ),
        migrations.AddField(
            model_name='message',
            name='response',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='simai.response', verbose_name='OpenAI Response'),
        ),
        migrations.AddField(
            model_name='message',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='message',
            name='simulation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='simcore.simulation'),
        ),
        migrations.AddField(
            model_name='messagemedialink',
            name='media',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simcore.simulationimage'),
        ),
        migrations.AddField(
            model_name='messagemedialink',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chatlab.message'),
        ),
        migrations.AddField(
            model_name='message',
            name='media',
            field=models.ManyToManyField(blank=True, related_name='messages', through='chatlab.MessageMediaLink', to='simcore.simulationimage'),
        ),
        migrations.AlterUniqueTogether(
            name='messagemedialink',
            unique_together={('message', 'media')},
        ),
        migrations.AlterUniqueTogether(
            name='message',
            unique_together={('simulation', 'order')},
        ),
    ]
