# Generated by Django 5.2 on 2025-04-20 14:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chatlab', '0001_initial'),
        ('simai', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='response',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='simai.response', verbose_name='OpenAI Response'),
        ),
        migrations.AddField(
            model_name='message',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='simulation',
            name='prompt',
            field=models.ForeignKey(help_text='The prompt to use as AI instructions.', on_delete=django.db.models.deletion.RESTRICT, to='simai.prompt'),
        ),
        migrations.AddField(
            model_name='simulation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='message',
            name='simulation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chatlab.simulation'),
        ),
        migrations.AddField(
            model_name='simulationmetadata',
            name='simulation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metadata', to='chatlab.simulation'),
        ),
        migrations.AlterUniqueTogether(
            name='message',
            unique_together={('simulation', 'order')},
        ),
    ]
