# Generated by Django 5.2 on 2025-04-18 18:16

import ChatLab.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ChatLab', '0001_initial'),
        ('SimManAI', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='response',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='SimManAI.response', verbose_name='OpenAI Response'),
        ),
        migrations.AddField(
            model_name='message',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='prompt',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_prompts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='prompt',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_prompts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='simulation',
            name='prompt',
            field=models.ForeignKey(blank=True, default=ChatLab.models.get_default_prompt, help_text='The prompt to use as AI instructions.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='ChatLab.prompt'),
        ),
        migrations.AddField(
            model_name='simulation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='message',
            name='simulation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ChatLab.simulation'),
        ),
        migrations.AddField(
            model_name='simulationmetadata',
            name='simulation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metadata', to='ChatLab.simulation'),
        ),
        migrations.AlterUniqueTogether(
            name='message',
            unique_together={('simulation', 'order')},
        ),
    ]
