# Generated by Django 6.0 on 2025-12-31 00:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chatlab', '0001_initial'),
        ('simulation', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='simulation',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_session', related_query_name='%(app_label)s_session', to='simulation.simulation'),
        ),
        migrations.AddField(
            model_name='message',
            name='response',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='input', to='simulation.airesponse', verbose_name='AI Response'),
        ),
        migrations.AddField(
            model_name='message',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='message',
            name='simulation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='input', to='simulation.simulation'),
        ),
        migrations.AddField(
            model_name='messagemedialink',
            name='media',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simulation.simulationimage'),
        ),
        migrations.AddField(
            model_name='messagemedialink',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chatlab.message'),
        ),
        migrations.AddField(
            model_name='message',
            name='media',
            field=models.ManyToManyField(blank=True, related_name='input', through='chatlab.MessageMediaLink', to='simulation.simulationimage'),
        ),
        migrations.AlterUniqueTogether(
            name='messagemedialink',
            unique_together={('message', 'media')},
        ),
        migrations.AlterUniqueTogether(
            name='message',
            unique_together={('simulation', 'order')},
        ),
    ]
