# Generated by Django 6.0 on 2026-01-16 22:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatlab', '0002_initial'),
        ('orchestrai_django', '0005_add_ai_audit_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='ai_response_audit',
            field=models.ForeignKey(blank=True, help_text='Link to AI audit record that produced this message', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='orchestrai_django.airesponseaudit'),
        ),
    ]
