# Generated by Django 6.0.2 on 2026-02-19 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatlab', '0002_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='message',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='message',
            name='image_requested',
            field=models.BooleanField(default=False, help_text='Whether this message references images/scans that should be generated'),
        ),
        migrations.RemoveField(
            model_name='message',
            name='order',
        ),
    ]
