# Generated by Django 5.2 on 2025-04-19 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChatLab', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simulationmetadata',
            name='key',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='simulationmetadata',
            name='value',
            field=models.CharField(max_length=2000),
        ),
    ]
